`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 02:42:46 CST (May  4 2021 18:42:46 UTC)

module DC_Filter_LessThan_12Ux9U_1U_4(in2, in1, out1);
  input [11:0] in2;
  input [8:0] in1;
  output out1;
  wire [11:0] in2;
  wire [8:0] in1;
  wire out1;
  wire gt_21_21_n_0, gt_21_21_n_1, gt_21_21_n_2, gt_21_21_n_3,
       gt_21_21_n_4, gt_21_21_n_5, gt_21_21_n_6, gt_21_21_n_7;
  wire gt_21_21_n_8, gt_21_21_n_9, gt_21_21_n_10, gt_21_21_n_11,
       gt_21_21_n_12, gt_21_21_n_13, gt_21_21_n_14, gt_21_21_n_15;
  wire gt_21_21_n_16, gt_21_21_n_17, gt_21_21_n_18, gt_21_21_n_19,
       gt_21_21_n_20, gt_21_21_n_21, gt_21_21_n_22, gt_21_21_n_23;
  wire gt_21_21_n_24;
  NOR4X1 gt_21_21_g293(.A (in2[11]), .B (in2[10]), .C (in2[9]), .D
       (gt_21_21_n_24), .Y (out1));
  OAI22X1 gt_21_21_g294(.A0 (gt_21_21_n_12), .A1 (gt_21_21_n_23), .B0
       (gt_21_21_n_1), .B1 (in1[8]), .Y (gt_21_21_n_24));
  AOI31X1 gt_21_21_g295(.A0 (gt_21_21_n_22), .A1 (gt_21_21_n_10), .A2
       (gt_21_21_n_13), .B0 (gt_21_21_n_21), .Y (gt_21_21_n_23));
  AOI32X1 gt_21_21_g296(.A0 (gt_21_21_n_15), .A1 (gt_21_21_n_7), .A2
       (gt_21_21_n_20), .B0 (in1[4]), .B1 (gt_21_21_n_5), .Y
       (gt_21_21_n_22));
  OAI211X1 gt_21_21_g297(.A0 (gt_21_21_n_0), .A1 (in1[7]), .B0
       (gt_21_21_n_14), .C0 (gt_21_21_n_19), .Y (gt_21_21_n_21));
  OAI211X1 gt_21_21_g298(.A0 (gt_21_21_n_4), .A1 (in2[2]), .B0
       (gt_21_21_n_8), .C0 (gt_21_21_n_18), .Y (gt_21_21_n_20));
  NAND2X1 gt_21_21_g299(.A (gt_21_21_n_13), .B (gt_21_21_n_17), .Y
       (gt_21_21_n_19));
  OAI21X1 gt_21_21_g300(.A0 (in1[1]), .A1 (gt_21_21_n_6), .B0
       (gt_21_21_n_16), .Y (gt_21_21_n_18));
  OAI32X1 gt_21_21_g301(.A0 (gt_21_21_n_5), .A1 (in1[4]), .A2
       (gt_21_21_n_11), .B0 (gt_21_21_n_3), .B1 (in1[5]), .Y
       (gt_21_21_n_17));
  OAI2BB1X1 gt_21_21_g302(.A0N (in1[1]), .A1N (gt_21_21_n_6), .B0
       (in2[1]), .Y (gt_21_21_n_16));
  NAND3X1 gt_21_21_g303(.A (in2[2]), .B (gt_21_21_n_4), .C
       (gt_21_21_n_8), .Y (gt_21_21_n_15));
  NAND3BXL gt_21_21_g304(.AN (in1[6]), .B (in2[6]), .C (gt_21_21_n_9),
       .Y (gt_21_21_n_14));
  OA21X1 gt_21_21_g305(.A0 (gt_21_21_n_2), .A1 (in2[6]), .B0
       (gt_21_21_n_9), .Y (gt_21_21_n_13));
  NOR2BX1 gt_21_21_g306(.AN (in1[8]), .B (in2[8]), .Y (gt_21_21_n_12));
  INVX1 gt_21_21_g307(.A (gt_21_21_n_10), .Y (gt_21_21_n_11));
  NAND2X1 gt_21_21_g308(.A (in1[5]), .B (gt_21_21_n_3), .Y
       (gt_21_21_n_10));
  NAND2X1 gt_21_21_g309(.A (in1[7]), .B (gt_21_21_n_0), .Y
       (gt_21_21_n_9));
  NAND2BX1 gt_21_21_g310(.AN (in2[3]), .B (in1[3]), .Y (gt_21_21_n_8));
  NAND2BXL gt_21_21_g311(.AN (in1[3]), .B (in2[3]), .Y (gt_21_21_n_7));
  NOR2BX1 gt_21_21_g312(.AN (in1[0]), .B (in2[0]), .Y (gt_21_21_n_6));
  INVX1 gt_21_21_g313(.A (in2[4]), .Y (gt_21_21_n_5));
  INVX1 gt_21_21_g314(.A (in1[2]), .Y (gt_21_21_n_4));
  INVX1 gt_21_21_g315(.A (in2[5]), .Y (gt_21_21_n_3));
  INVX1 gt_21_21_g316(.A (in1[6]), .Y (gt_21_21_n_2));
  INVX1 gt_21_21_g317(.A (in2[8]), .Y (gt_21_21_n_1));
  INVX1 gt_21_21_g318(.A (in2[7]), .Y (gt_21_21_n_0));
endmodule


