`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  4 2021 17:09:11 CST (May  4 2021 09:09:11 UTC)

module DC_Filter_Add3s28And2u1u1s32_4(in4, in3, in2, in1, out1);
  input [31:0] in4;
  input in3, in2;
  input [27:0] in1;
  output [31:0] out1;
  wire [31:0] in4;
  wire in3, in2;
  wire [27:0] in1;
  wire [31:0] out1;
  wire asc002, csa_tree_add_35_2_groupi_n_0,
       csa_tree_add_35_2_groupi_n_1, csa_tree_add_35_2_groupi_n_2,
       csa_tree_add_35_2_groupi_n_3, csa_tree_add_35_2_groupi_n_4,
       csa_tree_add_35_2_groupi_n_5, csa_tree_add_35_2_groupi_n_7;
  wire csa_tree_add_35_2_groupi_n_9, csa_tree_add_35_2_groupi_n_11,
       csa_tree_add_35_2_groupi_n_13, csa_tree_add_35_2_groupi_n_15,
       csa_tree_add_35_2_groupi_n_17, csa_tree_add_35_2_groupi_n_19,
       csa_tree_add_35_2_groupi_n_21, csa_tree_add_35_2_groupi_n_23;
  wire csa_tree_add_35_2_groupi_n_25, csa_tree_add_35_2_groupi_n_27,
       csa_tree_add_35_2_groupi_n_29, csa_tree_add_35_2_groupi_n_31,
       csa_tree_add_35_2_groupi_n_33, csa_tree_add_35_2_groupi_n_35,
       csa_tree_add_35_2_groupi_n_37, csa_tree_add_35_2_groupi_n_39;
  wire csa_tree_add_35_2_groupi_n_41, csa_tree_add_35_2_groupi_n_43,
       csa_tree_add_35_2_groupi_n_45, csa_tree_add_35_2_groupi_n_47,
       csa_tree_add_35_2_groupi_n_49, csa_tree_add_35_2_groupi_n_51,
       csa_tree_add_35_2_groupi_n_53, csa_tree_add_35_2_groupi_n_55;
  wire csa_tree_add_35_2_groupi_n_57, csa_tree_add_35_2_groupi_n_59,
       csa_tree_add_35_2_groupi_n_61, csa_tree_add_35_2_groupi_n_63,
       csa_tree_add_35_2_groupi_n_65;
  AND2XL g11(.A (in3), .B (in2), .Y (asc002));
  XOR2XL csa_tree_add_35_2_groupi_g648(.A
       (csa_tree_add_35_2_groupi_n_4), .B
       (csa_tree_add_35_2_groupi_n_65), .Y (out1[31]));
  ADDFX1 csa_tree_add_35_2_groupi_g649(.A
       (csa_tree_add_35_2_groupi_n_63), .B (in4[29]), .CI
       (csa_tree_add_35_2_groupi_n_1), .CO
       (csa_tree_add_35_2_groupi_n_65), .S (out1[30]));
  ADDFX1 csa_tree_add_35_2_groupi_g650(.A
       (csa_tree_add_35_2_groupi_n_61), .B (in4[28]), .CI
       (csa_tree_add_35_2_groupi_n_2), .CO
       (csa_tree_add_35_2_groupi_n_63), .S (out1[29]));
  ADDFX1 csa_tree_add_35_2_groupi_g651(.A
       (csa_tree_add_35_2_groupi_n_59), .B
       (csa_tree_add_35_2_groupi_n_0), .CI
       (csa_tree_add_35_2_groupi_n_3), .CO
       (csa_tree_add_35_2_groupi_n_61), .S (out1[28]));
  ADDFX1 csa_tree_add_35_2_groupi_g652(.A
       (csa_tree_add_35_2_groupi_n_57), .B (in4[27]), .CI (in1[27]),
       .CO (csa_tree_add_35_2_groupi_n_59), .S (out1[27]));
  ADDFX1 csa_tree_add_35_2_groupi_g653(.A
       (csa_tree_add_35_2_groupi_n_55), .B (in4[26]), .CI (in1[26]),
       .CO (csa_tree_add_35_2_groupi_n_57), .S (out1[26]));
  ADDFX1 csa_tree_add_35_2_groupi_g654(.A
       (csa_tree_add_35_2_groupi_n_53), .B (in4[25]), .CI (in1[25]),
       .CO (csa_tree_add_35_2_groupi_n_55), .S (out1[25]));
  ADDFX1 csa_tree_add_35_2_groupi_g655(.A
       (csa_tree_add_35_2_groupi_n_51), .B (in4[24]), .CI (in1[24]),
       .CO (csa_tree_add_35_2_groupi_n_53), .S (out1[24]));
  ADDFX1 csa_tree_add_35_2_groupi_g656(.A
       (csa_tree_add_35_2_groupi_n_49), .B (in4[23]), .CI (in1[23]),
       .CO (csa_tree_add_35_2_groupi_n_51), .S (out1[23]));
  ADDFX1 csa_tree_add_35_2_groupi_g657(.A
       (csa_tree_add_35_2_groupi_n_47), .B (in4[22]), .CI (in1[22]),
       .CO (csa_tree_add_35_2_groupi_n_49), .S (out1[22]));
  ADDFX1 csa_tree_add_35_2_groupi_g658(.A
       (csa_tree_add_35_2_groupi_n_45), .B (in4[21]), .CI (in1[21]),
       .CO (csa_tree_add_35_2_groupi_n_47), .S (out1[21]));
  ADDFX1 csa_tree_add_35_2_groupi_g659(.A
       (csa_tree_add_35_2_groupi_n_43), .B (in4[20]), .CI (in1[20]),
       .CO (csa_tree_add_35_2_groupi_n_45), .S (out1[20]));
  ADDFX1 csa_tree_add_35_2_groupi_g660(.A
       (csa_tree_add_35_2_groupi_n_41), .B (in4[19]), .CI (in1[19]),
       .CO (csa_tree_add_35_2_groupi_n_43), .S (out1[19]));
  ADDFX1 csa_tree_add_35_2_groupi_g661(.A
       (csa_tree_add_35_2_groupi_n_39), .B (in4[18]), .CI (in1[18]),
       .CO (csa_tree_add_35_2_groupi_n_41), .S (out1[18]));
  ADDFX1 csa_tree_add_35_2_groupi_g662(.A
       (csa_tree_add_35_2_groupi_n_37), .B (in4[17]), .CI (in1[17]),
       .CO (csa_tree_add_35_2_groupi_n_39), .S (out1[17]));
  ADDFX1 csa_tree_add_35_2_groupi_g663(.A
       (csa_tree_add_35_2_groupi_n_35), .B (in4[16]), .CI (in1[16]),
       .CO (csa_tree_add_35_2_groupi_n_37), .S (out1[16]));
  ADDFX1 csa_tree_add_35_2_groupi_g664(.A
       (csa_tree_add_35_2_groupi_n_33), .B (in4[15]), .CI (in1[15]),
       .CO (csa_tree_add_35_2_groupi_n_35), .S (out1[15]));
  ADDFX1 csa_tree_add_35_2_groupi_g665(.A
       (csa_tree_add_35_2_groupi_n_31), .B (in4[14]), .CI (in1[14]),
       .CO (csa_tree_add_35_2_groupi_n_33), .S (out1[14]));
  ADDFX1 csa_tree_add_35_2_groupi_g666(.A
       (csa_tree_add_35_2_groupi_n_29), .B (in4[13]), .CI (in1[13]),
       .CO (csa_tree_add_35_2_groupi_n_31), .S (out1[13]));
  ADDFX1 csa_tree_add_35_2_groupi_g667(.A
       (csa_tree_add_35_2_groupi_n_27), .B (in4[12]), .CI (in1[12]),
       .CO (csa_tree_add_35_2_groupi_n_29), .S (out1[12]));
  ADDFX1 csa_tree_add_35_2_groupi_g668(.A
       (csa_tree_add_35_2_groupi_n_25), .B (in4[11]), .CI (in1[11]),
       .CO (csa_tree_add_35_2_groupi_n_27), .S (out1[11]));
  ADDFX1 csa_tree_add_35_2_groupi_g669(.A
       (csa_tree_add_35_2_groupi_n_23), .B (in4[10]), .CI (in1[10]),
       .CO (csa_tree_add_35_2_groupi_n_25), .S (out1[10]));
  ADDFX1 csa_tree_add_35_2_groupi_g670(.A
       (csa_tree_add_35_2_groupi_n_21), .B (in4[9]), .CI (in1[9]), .CO
       (csa_tree_add_35_2_groupi_n_23), .S (out1[9]));
  ADDFX1 csa_tree_add_35_2_groupi_g671(.A
       (csa_tree_add_35_2_groupi_n_19), .B (in4[8]), .CI (in1[8]), .CO
       (csa_tree_add_35_2_groupi_n_21), .S (out1[8]));
  ADDFX1 csa_tree_add_35_2_groupi_g672(.A
       (csa_tree_add_35_2_groupi_n_17), .B (in4[7]), .CI (in1[7]), .CO
       (csa_tree_add_35_2_groupi_n_19), .S (out1[7]));
  ADDFX1 csa_tree_add_35_2_groupi_g673(.A
       (csa_tree_add_35_2_groupi_n_15), .B (in4[6]), .CI (in1[6]), .CO
       (csa_tree_add_35_2_groupi_n_17), .S (out1[6]));
  ADDFX1 csa_tree_add_35_2_groupi_g674(.A
       (csa_tree_add_35_2_groupi_n_13), .B (in4[5]), .CI (in1[5]), .CO
       (csa_tree_add_35_2_groupi_n_15), .S (out1[5]));
  ADDFX1 csa_tree_add_35_2_groupi_g675(.A
       (csa_tree_add_35_2_groupi_n_11), .B (in4[4]), .CI (in1[4]), .CO
       (csa_tree_add_35_2_groupi_n_13), .S (out1[4]));
  ADDFX1 csa_tree_add_35_2_groupi_g676(.A
       (csa_tree_add_35_2_groupi_n_9), .B (in4[3]), .CI (in1[3]), .CO
       (csa_tree_add_35_2_groupi_n_11), .S (out1[3]));
  ADDFX1 csa_tree_add_35_2_groupi_g677(.A
       (csa_tree_add_35_2_groupi_n_7), .B (in4[2]), .CI (in1[2]), .CO
       (csa_tree_add_35_2_groupi_n_9), .S (out1[2]));
  ADDFX1 csa_tree_add_35_2_groupi_g678(.A
       (csa_tree_add_35_2_groupi_n_5), .B (in4[1]), .CI (in1[1]), .CO
       (csa_tree_add_35_2_groupi_n_7), .S (out1[1]));
  ADDFX1 csa_tree_add_35_2_groupi_g679(.A (in1[0]), .B (in4[0]), .CI
       (asc002), .CO (csa_tree_add_35_2_groupi_n_5), .S (out1[0]));
  MXI2XL csa_tree_add_35_2_groupi_g680(.A (in4[30]), .B
       (csa_tree_add_35_2_groupi_n_1), .S0 (in4[31]), .Y
       (csa_tree_add_35_2_groupi_n_4));
  INVX1 csa_tree_add_35_2_groupi_g681(.A (in1[27]), .Y
       (csa_tree_add_35_2_groupi_n_3));
  INVX1 csa_tree_add_35_2_groupi_g682(.A (in4[29]), .Y
       (csa_tree_add_35_2_groupi_n_2));
  INVX1 csa_tree_add_35_2_groupi_g683(.A (in4[30]), .Y
       (csa_tree_add_35_2_groupi_n_1));
  INVX1 csa_tree_add_35_2_groupi_g684(.A (in4[28]), .Y
       (csa_tree_add_35_2_groupi_n_0));
endmodule

