`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 02:02:23 CST (May  4 2021 18:02:23 UTC)

module DC_Filter_Add_12U_167_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_0, add_21_2_n_4, add_21_2_n_5, add_21_2_n_6,
       add_21_2_n_7, add_21_2_n_8, add_21_2_n_9, add_21_2_n_11;
  wire add_21_2_n_12, add_21_2_n_13, add_21_2_n_14, add_21_2_n_15,
       add_21_2_n_16, add_21_2_n_17, add_21_2_n_18, add_21_2_n_19;
  wire add_21_2_n_20, add_21_2_n_21, add_21_2_n_22, add_21_2_n_24,
       add_21_2_n_26, add_21_2_n_27, add_21_2_n_28, add_21_2_n_29;
  wire add_21_2_n_30, add_21_2_n_31, add_21_2_n_34, add_21_2_n_35,
       add_21_2_n_36, add_21_2_n_61, add_21_2_n_62, add_21_2_n_63;
  wire add_21_2_n_72, add_21_2_n_73, add_21_2_n_74, add_21_2_n_76,
       add_21_2_n_77, add_21_2_n_78, add_21_2_n_79, add_21_2_n_80;
  wire add_21_2_n_81, add_21_2_n_82, add_21_2_n_85, add_21_2_n_86,
       add_21_2_n_87, add_21_2_n_89, add_21_2_n_90, add_21_2_n_91;
  wire add_21_2_n_92;
  INVX1 g7(.A (in1[0]), .Y (out1[0]));
  MXI2XL add_21_2_g221(.A (add_21_2_n_6), .B (in1[9]), .S0
       (add_21_2_n_35), .Y (out1[9]));
  MXI2XL add_21_2_g222(.A (add_21_2_n_11), .B (in1[11]), .S0
       (add_21_2_n_34), .Y (out1[11]));
  MXI2XL add_21_2_g223(.A (add_21_2_n_7), .B (in1[5]), .S0
       (add_21_2_n_27), .Y (out1[5]));
  MXI2XL add_21_2_g224(.A (add_21_2_n_5), .B (in1[10]), .S0
       (add_21_2_n_36), .Y (out1[10]));
  MXI2XL add_21_2_g225(.A (add_21_2_n_9), .B (in1[7]), .S0
       (add_21_2_n_29), .Y (out1[7]));
  MXI2XL add_21_2_g226(.A (add_21_2_n_8), .B (in1[8]), .S0
       (add_21_2_n_30), .Y (out1[8]));
  NOR2X1 add_21_2_g227(.A (add_21_2_n_15), .B (add_21_2_n_31), .Y
       (add_21_2_n_36));
  NOR2X1 add_21_2_g228(.A (add_21_2_n_8), .B (add_21_2_n_31), .Y
       (add_21_2_n_35));
  NOR2X1 add_21_2_g229(.A (add_21_2_n_17), .B (add_21_2_n_31), .Y
       (add_21_2_n_34));
  MXI2XL add_21_2_g230(.A (add_21_2_n_4), .B (in1[3]), .S0
       (add_21_2_n_21), .Y (out1[3]));
  MXI2XL add_21_2_g231(.A (add_21_2_n_77), .B (add_21_2_n_78), .S0
       (add_21_2_n_28), .Y (out1[6]));
  CLKINVX3 add_21_2_g233(.A (add_21_2_n_30), .Y (add_21_2_n_31));
  OAI21X4 add_21_2_g234(.A0 (add_21_2_n_14), .A1 (add_21_2_n_24), .B0
       (add_21_2_n_19), .Y (add_21_2_n_30));
  OAI21X1 add_21_2_g235(.A0 (add_21_2_n_79), .A1 (add_21_2_n_62), .B0
       (add_21_2_n_18), .Y (add_21_2_n_29));
  NOR2X1 add_21_2_g236(.A (add_21_2_n_72), .B (add_21_2_n_61), .Y
       (add_21_2_n_28));
  NOR2X1 add_21_2_g238(.A (in1[4]), .B (add_21_2_n_63), .Y
       (add_21_2_n_27));
  NOR2BX1 add_21_2_g239(.AN (in1[4]), .B (add_21_2_n_62), .Y
       (add_21_2_n_26));
  NAND2BX1 add_21_2_g240(.AN (add_21_2_n_20), .B (add_21_2_n_21), .Y
       (out1[2]));
  NOR2X2 add_21_2_g242(.A (add_21_2_n_16), .B (add_21_2_n_22), .Y
       (add_21_2_n_24));
  NOR2X2 add_21_2_g243(.A (add_21_2_n_4), .B (add_21_2_n_12), .Y
       (add_21_2_n_22));
  NAND2X1 add_21_2_g244(.A (add_21_2_n_90), .B (add_21_2_n_86), .Y
       (add_21_2_n_21));
  NOR2X1 add_21_2_g245(.A (add_21_2_n_89), .B (add_21_2_n_85), .Y
       (add_21_2_n_20));
  NAND2X2 add_21_2_g246(.A (add_21_2_n_13), .B (add_21_2_n_0), .Y
       (add_21_2_n_19));
  NAND2X1 add_21_2_g247(.A (add_21_2_n_76), .B (add_21_2_n_73), .Y
       (add_21_2_n_18));
  OR2XL add_21_2_g248(.A (add_21_2_n_5), .B (add_21_2_n_15), .Y
       (add_21_2_n_17));
  NOR2X2 add_21_2_g250(.A (add_21_2_n_92), .B (add_21_2_n_4), .Y
       (add_21_2_n_16));
  NAND2X1 add_21_2_g251(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_15));
  INVX1 add_21_2_g252(.A (add_21_2_n_13), .Y (add_21_2_n_14));
  NOR2X2 add_21_2_g253(.A (add_21_2_n_82), .B (add_21_2_n_9), .Y
       (add_21_2_n_13));
  NAND2X8 add_21_2_g255(.A (in1[1]), .B (in1[0]), .Y (add_21_2_n_12));
  INVXL add_21_2_g256(.A (in1[11]), .Y (add_21_2_n_11));
  CLKINVX2 add_21_2_g260(.A (in1[7]), .Y (add_21_2_n_9));
  INVX1 add_21_2_g261(.A (in1[8]), .Y (add_21_2_n_8));
  CLKINVX2 add_21_2_g262(.A (in1[5]), .Y (add_21_2_n_7));
  INVXL add_21_2_g263(.A (in1[9]), .Y (add_21_2_n_6));
  INVX1 add_21_2_g264(.A (in1[10]), .Y (add_21_2_n_5));
  CLKINVX3 add_21_2_g265(.A (in1[3]), .Y (add_21_2_n_4));
  OR2XL add_21_2_g2(.A (add_21_2_n_26), .B (add_21_2_n_27), .Y
       (out1[4]));
  XOR2XL add_21_2_g267(.A (in1[1]), .B (in1[0]), .Y (out1[1]));
  NAND2BX4 add_21_2_g268(.AN (in1[4]), .B (add_21_2_n_7), .Y
       (add_21_2_n_0));
  INVXL add_21_2_fopt(.A (add_21_2_n_62), .Y (add_21_2_n_61));
  CLKINVX1 add_21_2_fopt269(.A (add_21_2_n_62), .Y (add_21_2_n_63));
  BUFX3 add_21_2_fopt270(.A (add_21_2_n_24), .Y (add_21_2_n_62));
  INVXL add_21_2_fopt276(.A (add_21_2_n_74), .Y (add_21_2_n_72));
  INVXL add_21_2_fopt277(.A (add_21_2_n_74), .Y (add_21_2_n_73));
  INVXL add_21_2_fopt278(.A (add_21_2_n_0), .Y (add_21_2_n_74));
  INVXL add_21_2_fopt279(.A (add_21_2_n_81), .Y (add_21_2_n_76));
  INVXL add_21_2_fopt280(.A (add_21_2_n_78), .Y (add_21_2_n_77));
  INVXL add_21_2_fopt281(.A (add_21_2_n_80), .Y (add_21_2_n_78));
  INVXL add_21_2_fopt282(.A (add_21_2_n_80), .Y (add_21_2_n_79));
  INVXL add_21_2_fopt283(.A (add_21_2_n_81), .Y (add_21_2_n_80));
  INVXL add_21_2_fopt284(.A (in1[6]), .Y (add_21_2_n_81));
  CLKINVX3 add_21_2_fopt285(.A (in1[6]), .Y (add_21_2_n_82));
  INVXL add_21_2_fopt286(.A (add_21_2_n_87), .Y (add_21_2_n_85));
  INVXL add_21_2_fopt287(.A (add_21_2_n_87), .Y (add_21_2_n_86));
  INVXL add_21_2_fopt288(.A (add_21_2_n_12), .Y (add_21_2_n_87));
  INVXL add_21_2_fopt289(.A (add_21_2_n_91), .Y (add_21_2_n_89));
  INVXL add_21_2_fopt290(.A (add_21_2_n_91), .Y (add_21_2_n_90));
  BUFX2 add_21_2_fopt291(.A (in1[2]), .Y (add_21_2_n_91));
  CLKINVX3 add_21_2_fopt292(.A (in1[2]), .Y (add_21_2_n_92));
endmodule

