`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 02:00:58 CST (May  4 2021 18:00:58 UTC)

module DC_Filter_Add_12U_4_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_6, add_21_2_n_7, add_21_2_n_8, add_21_2_n_9,
       add_21_2_n_10, add_21_2_n_11, add_21_2_n_12, add_21_2_n_13;
  wire add_21_2_n_14, add_21_2_n_15, add_21_2_n_16, add_21_2_n_17,
       add_21_2_n_18, add_21_2_n_19, add_21_2_n_20, add_21_2_n_21;
  wire add_21_2_n_22, add_21_2_n_23, add_21_2_n_24, add_21_2_n_27,
       add_21_2_n_29, add_21_2_n_30, add_21_2_n_31, add_21_2_n_64;
  wire add_21_2_n_69, add_21_2_n_70, add_21_2_n_71, add_21_2_n_72,
       add_21_2_n_78, add_21_2_n_79, add_21_2_n_80, add_21_2_n_81;
  wire add_21_2_n_82, add_21_2_n_83, add_21_2_n_84;
  assign out1[0] = in1[0];
  INVX1 g7(.A (in1[1]), .Y (out1[1]));
  MXI2XL add_21_2_g206(.A (add_21_2_n_8), .B (in1[5]), .S0
       (add_21_2_n_20), .Y (out1[5]));
  MXI2X1 add_21_2_g207(.A (add_21_2_n_9), .B (in1[10]), .S0
       (add_21_2_n_31), .Y (out1[10]));
  MXI2X1 add_21_2_g208(.A (add_21_2_n_7), .B (in1[8]), .S0
       (add_21_2_n_69), .Y (out1[8]));
  NOR2X1 add_21_2_g210(.A (add_21_2_n_12), .B (add_21_2_n_70), .Y
       (add_21_2_n_31));
  NOR2X2 add_21_2_g211(.A (add_21_2_n_7), .B (add_21_2_n_71), .Y
       (add_21_2_n_30));
  NOR2X2 add_21_2_g212(.A (add_21_2_n_18), .B (add_21_2_n_72), .Y
       (add_21_2_n_29));
  MXI2XL add_21_2_g214(.A (in1[6]), .B (add_21_2_n_6), .S0
       (add_21_2_n_23), .Y (out1[6]));
  AOI21X1 add_21_2_g215(.A0 (in1[6]), .A1 (add_21_2_n_78), .B0
       (add_21_2_n_64), .Y (add_21_2_n_27));
  NAND2BX1 add_21_2_g216(.AN (add_21_2_n_20), .B (add_21_2_n_19), .Y
       (out1[4]));
  NAND2X2 add_21_2_g218(.A (add_21_2_n_21), .B (add_21_2_n_22), .Y
       (add_21_2_n_24));
  NOR2BX1 add_21_2_g219(.AN (add_21_2_n_14), .B (add_21_2_n_79), .Y
       (add_21_2_n_23));
  NAND2X4 add_21_2_g220(.A (in1[6]), .B (add_21_2_n_16), .Y
       (add_21_2_n_22));
  NOR2X2 add_21_2_g221(.A (in1[7]), .B (add_21_2_n_17), .Y
       (add_21_2_n_21));
  NOR2X1 add_21_2_g222(.A (in1[4]), .B (add_21_2_n_81), .Y
       (add_21_2_n_20));
  NAND2X1 add_21_2_g223(.A (in1[4]), .B (add_21_2_n_80), .Y
       (add_21_2_n_19));
  OR2XL add_21_2_g224(.A (add_21_2_n_9), .B (add_21_2_n_12), .Y
       (add_21_2_n_18));
  NOR2X2 add_21_2_g225(.A (add_21_2_n_6), .B (add_21_2_n_14), .Y
       (add_21_2_n_17));
  NAND2X4 add_21_2_g227(.A (add_21_2_n_11), .B (add_21_2_n_13), .Y
       (add_21_2_n_16));
  NOR2X1 add_21_2_g229(.A (in1[2]), .B (in1[1]), .Y (add_21_2_n_15));
  NOR2X6 add_21_2_g230(.A (in1[5]), .B (in1[4]), .Y (add_21_2_n_14));
  NAND2X6 add_21_2_g231(.A (in1[3]), .B (in1[1]), .Y (add_21_2_n_13));
  NAND2X1 add_21_2_g232(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_12));
  NAND2X8 add_21_2_g233(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_11));
  NAND2X1 add_21_2_g234(.A (in1[2]), .B (in1[1]), .Y (add_21_2_n_10));
  INVX1 add_21_2_g236(.A (in1[10]), .Y (add_21_2_n_9));
  INVXL add_21_2_g240(.A (in1[5]), .Y (add_21_2_n_8));
  INVX1 add_21_2_g241(.A (in1[8]), .Y (add_21_2_n_7));
  CLKINVX3 add_21_2_g242(.A (in1[6]), .Y (add_21_2_n_6));
  NAND2BX1 add_21_2_g2(.AN (add_21_2_n_15), .B (add_21_2_n_10), .Y
       (out1[2]));
  XOR2XL add_21_2_g243(.A (in1[11]), .B (add_21_2_n_29), .Y (out1[11]));
  CLKXOR2X1 add_21_2_g244(.A (in1[7]), .B (add_21_2_n_27), .Y
       (out1[7]));
  XNOR2X1 add_21_2_g245(.A (in1[3]), .B (add_21_2_n_15), .Y (out1[3]));
  XOR2XL add_21_2_g246(.A (in1[9]), .B (add_21_2_n_30), .Y (out1[9]));
  BUFX2 add_21_2_fopt254(.A (add_21_2_n_17), .Y (add_21_2_n_64));
  INVXL add_21_2_fopt257(.A (add_21_2_n_70), .Y (add_21_2_n_69));
  CLKINVX1 add_21_2_fopt258(.A (add_21_2_n_24), .Y (add_21_2_n_70));
  CLKINVX1 add_21_2_fopt259(.A (add_21_2_n_24), .Y (add_21_2_n_71));
  CLKINVX1 add_21_2_fopt260(.A (add_21_2_n_24), .Y (add_21_2_n_72));
  INVXL add_21_2_fopt263(.A (add_21_2_n_84), .Y (add_21_2_n_78));
  BUFX2 add_21_2_fopt264(.A (add_21_2_n_83), .Y (add_21_2_n_79));
  INVXL add_21_2_fopt265(.A (add_21_2_n_82), .Y (add_21_2_n_80));
  INVXL add_21_2_fopt266(.A (add_21_2_n_82), .Y (add_21_2_n_81));
  INVXL add_21_2_fopt267(.A (add_21_2_n_83), .Y (add_21_2_n_82));
  INVXL add_21_2_fopt268(.A (add_21_2_n_84), .Y (add_21_2_n_83));
  INVXL add_21_2_fopt269(.A (add_21_2_n_16), .Y (add_21_2_n_84));
endmodule

