`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 02:04:30 CST (May  4 2021 18:04:30 UTC)

module DC_Filter_Add2i108Mul2i258Add3i1u1Mul2i3u2_1(in2, in1, out1);
  input [1:0] in2;
  input in1;
  output [11:0] out1;
  wire [1:0] in2;
  wire in1;
  wire [11:0] out1;
  wire asc001_9_, csa_tree_add_29_2_groupi_n_0,
       csa_tree_add_29_2_groupi_n_1, csa_tree_add_29_2_groupi_n_2,
       csa_tree_add_29_2_groupi_n_3, csa_tree_add_29_2_groupi_n_5,
       csa_tree_add_35_2_groupi_n_1, csa_tree_add_35_2_groupi_n_3;
  wire csa_tree_add_35_2_groupi_n_10;
  assign out1[0] = 1'b0;
  assign out1[1] = out1[8];
  assign out1[5] = out1[6];
  CLKINVX2 g11(.A (out1[6]), .Y (out1[7]));
  CLKINVX1 fopt(.A (out1[2]), .Y (out1[9]));
  CLKINVX1 fopt13(.A (asc001_9_), .Y (out1[2]));
  ADDHX1 csa_tree_add_29_2_groupi_g86(.A (in2[1]), .B
       (csa_tree_add_29_2_groupi_n_5), .CO (out1[11]), .S (out1[10]));
  ADDFX1 csa_tree_add_29_2_groupi_g87(.A (in2[1]), .B (in2[0]), .CI
       (csa_tree_add_29_2_groupi_n_0), .CO
       (csa_tree_add_29_2_groupi_n_5), .S (asc001_9_));
  NAND2X1 csa_tree_add_29_2_groupi_g88(.A
       (csa_tree_add_29_2_groupi_n_3), .B
       (csa_tree_add_29_2_groupi_n_0), .Y (out1[8]));
  NAND2X1 csa_tree_add_29_2_groupi_g90(.A (in2[0]), .B (in1), .Y
       (csa_tree_add_29_2_groupi_n_3));
  CLKINVX4 csa_tree_add_29_2_groupi_g92(.A (in2[0]), .Y
       (csa_tree_add_29_2_groupi_n_2));
  CLKINVX2 csa_tree_add_29_2_groupi_g93(.A (in1), .Y
       (csa_tree_add_29_2_groupi_n_1));
  NAND2X2 csa_tree_add_29_2_groupi_g94(.A
       (csa_tree_add_29_2_groupi_n_2), .B
       (csa_tree_add_29_2_groupi_n_1), .Y
       (csa_tree_add_29_2_groupi_n_0));
  MXI2X1 csa_tree_add_35_2_groupi_g156(.A (out1[11]), .B
       (csa_tree_add_35_2_groupi_n_1), .S0
       (csa_tree_add_35_2_groupi_n_3), .Y (out1[4]));
  OAI21X2 csa_tree_add_35_2_groupi_g157(.A0 (asc001_9_), .A1
       (out1[10]), .B0 (out1[11]), .Y (out1[6]));
  MXI2XL csa_tree_add_35_2_groupi_g158(.A (asc001_9_), .B
       (csa_tree_add_35_2_groupi_n_10), .S0 (out1[10]), .Y (out1[3]));
  NOR2X2 csa_tree_add_35_2_groupi_g159(.A (asc001_9_), .B (out1[10]),
       .Y (csa_tree_add_35_2_groupi_n_3));
  INVXL csa_tree_add_35_2_groupi_g161(.A (out1[11]), .Y
       (csa_tree_add_35_2_groupi_n_1));
  INVXL csa_tree_add_35_2_groupi_fopt(.A (asc001_9_), .Y
       (csa_tree_add_35_2_groupi_n_10));
endmodule

