`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 02:02:24 CST (May  4 2021 18:02:24 UTC)

module DC_Filter_Add_12U_169_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_0, add_21_2_n_3, add_21_2_n_4, add_21_2_n_5,
       add_21_2_n_6, add_21_2_n_7, add_21_2_n_9, add_21_2_n_10;
  wire add_21_2_n_11, add_21_2_n_12, add_21_2_n_13, add_21_2_n_14,
       add_21_2_n_15, add_21_2_n_16, add_21_2_n_17, add_21_2_n_19;
  wire add_21_2_n_20, add_21_2_n_21, add_21_2_n_22, add_21_2_n_23,
       add_21_2_n_24, add_21_2_n_25, add_21_2_n_26, add_21_2_n_29;
  wire add_21_2_n_30, add_21_2_n_31, add_21_2_n_32, add_21_2_n_33,
       add_21_2_n_36, add_21_2_n_37, add_21_2_n_65, add_21_2_n_66;
  wire add_21_2_n_68, add_21_2_n_69, add_21_2_n_70;
  INVX1 g7(.A (in1[0]), .Y (out1[0]));
  MXI2X1 add_21_2_g221(.A (in1[9]), .B (add_21_2_n_10), .S0
       (add_21_2_n_37), .Y (out1[9]));
  MXI2X1 add_21_2_g222(.A (in1[11]), .B (add_21_2_n_11), .S0
       (add_21_2_n_36), .Y (out1[11]));
  MXI2XL add_21_2_g223(.A (add_21_2_n_6), .B (in1[5]), .S0
       (add_21_2_n_30), .Y (out1[5]));
  MXI2X1 add_21_2_g224(.A (in1[10]), .B (add_21_2_n_7), .S0
       (add_21_2_n_0), .Y (out1[10]));
  MXI2XL add_21_2_g225(.A (add_21_2_n_68), .B (add_21_2_n_69), .S0
       (add_21_2_n_32), .Y (out1[7]));
  NAND2X1 add_21_2_g228(.A (in1[8]), .B (add_21_2_n_33), .Y
       (add_21_2_n_37));
  NAND2X1 add_21_2_g229(.A (add_21_2_n_19), .B (add_21_2_n_33), .Y
       (add_21_2_n_36));
  MXI2XL add_21_2_g230(.A (in1[3]), .B (add_21_2_n_5), .S0
       (add_21_2_n_24), .Y (out1[3]));
  MXI2XL add_21_2_g231(.A (in1[6]), .B (add_21_2_n_4), .S0
       (add_21_2_n_31), .Y (out1[6]));
  OAI21X2 add_21_2_g234(.A0 (add_21_2_n_15), .A1 (add_21_2_n_26), .B0
       (add_21_2_n_21), .Y (add_21_2_n_33));
  AOI21X1 add_21_2_g235(.A0 (in1[6]), .A1 (add_21_2_n_66), .B0
       (add_21_2_n_20), .Y (add_21_2_n_32));
  NOR2X1 add_21_2_g236(.A (add_21_2_n_13), .B (add_21_2_n_66), .Y
       (add_21_2_n_31));
  NOR2X1 add_21_2_g238(.A (in1[4]), .B (add_21_2_n_66), .Y
       (add_21_2_n_30));
  NOR2BX1 add_21_2_g239(.AN (in1[4]), .B (add_21_2_n_65), .Y
       (add_21_2_n_29));
  NAND2BXL add_21_2_g240(.AN (add_21_2_n_24), .B (add_21_2_n_23), .Y
       (out1[2]));
  NOR2X4 add_21_2_g242(.A (add_21_2_n_3), .B (add_21_2_n_25), .Y
       (add_21_2_n_26));
  NOR2X4 add_21_2_g243(.A (add_21_2_n_5), .B (add_21_2_n_17), .Y
       (add_21_2_n_25));
  NOR2X1 add_21_2_g244(.A (in1[2]), .B (add_21_2_n_22), .Y
       (add_21_2_n_24));
  NAND2X1 add_21_2_g245(.A (in1[2]), .B (add_21_2_n_22), .Y
       (add_21_2_n_23));
  INVX1 add_21_2_g246(.A (add_21_2_n_17), .Y (add_21_2_n_22));
  NAND2X1 add_21_2_g247(.A (add_21_2_n_13), .B (add_21_2_n_14), .Y
       (add_21_2_n_21));
  NOR2X1 add_21_2_g248(.A (add_21_2_n_4), .B (add_21_2_n_12), .Y
       (add_21_2_n_20));
  NOR2X1 add_21_2_g249(.A (add_21_2_n_7), .B (add_21_2_n_16), .Y
       (add_21_2_n_19));
  MXI2XL add_21_2_g250(.A (in1[1]), .B (add_21_2_n_9), .S0 (in1[0]), .Y
       (out1[1]));
  NOR2X4 add_21_2_g253(.A (in1[1]), .B (in1[0]), .Y (add_21_2_n_17));
  NAND2X1 add_21_2_g255(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_16));
  INVX1 add_21_2_g256(.A (add_21_2_n_14), .Y (add_21_2_n_15));
  NOR2X4 add_21_2_g257(.A (add_21_2_n_4), .B (add_21_2_n_70), .Y
       (add_21_2_n_14));
  INVX1 add_21_2_g258(.A (add_21_2_n_12), .Y (add_21_2_n_13));
  NOR2X4 add_21_2_g259(.A (in1[5]), .B (in1[4]), .Y (add_21_2_n_12));
  INVXL add_21_2_g260(.A (in1[11]), .Y (add_21_2_n_11));
  INVXL add_21_2_g261(.A (in1[9]), .Y (add_21_2_n_10));
  INVX1 add_21_2_g262(.A (in1[1]), .Y (add_21_2_n_9));
  INVX1 add_21_2_g264(.A (in1[10]), .Y (add_21_2_n_7));
  INVXL add_21_2_g265(.A (in1[5]), .Y (add_21_2_n_6));
  CLKINVX3 add_21_2_g267(.A (in1[3]), .Y (add_21_2_n_5));
  CLKINVX16 add_21_2_g268(.A (in1[6]), .Y (add_21_2_n_4));
  CLKAND2X6 add_21_2_g2(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_3));
  CLKXOR2X1 add_21_2_g269(.A (in1[8]), .B (add_21_2_n_33), .Y
       (out1[8]));
  OR2XL add_21_2_g270(.A (add_21_2_n_29), .B (add_21_2_n_30), .Y
       (out1[4]));
  NAND2BX1 add_21_2_g271(.AN (add_21_2_n_16), .B (add_21_2_n_33), .Y
       (add_21_2_n_0));
  CLKINVX1 add_21_2_fopt(.A (add_21_2_n_66), .Y (add_21_2_n_65));
  CLKINVX1 add_21_2_fopt274(.A (add_21_2_n_26), .Y (add_21_2_n_66));
  INVXL add_21_2_fopt275(.A (add_21_2_n_69), .Y (add_21_2_n_68));
  INVXL add_21_2_fopt276(.A (in1[7]), .Y (add_21_2_n_69));
  CLKINVX3 add_21_2_fopt277(.A (in1[7]), .Y (add_21_2_n_70));
endmodule

