`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:41:24 CST (May  4 2021 16:41:24 UTC)

module DC_Filter_Add_12U_118_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_2, add_21_2_n_3, add_21_2_n_4, add_21_2_n_5,
       add_21_2_n_6, add_21_2_n_7, add_21_2_n_8, add_21_2_n_9;
  wire add_21_2_n_10, add_21_2_n_11, add_21_2_n_12, add_21_2_n_14,
       add_21_2_n_15, add_21_2_n_16, add_21_2_n_17, add_21_2_n_18;
  wire add_21_2_n_22, add_21_2_n_23, add_21_2_n_24, add_21_2_n_46,
       add_21_2_n_47;
  assign out1[0] = in1[0];
  assign out1[1] = in1[1];
  assign out1[2] = in1[2];
  INVX1 g7(.A (in1[3]), .Y (out1[3]));
  MXI2XL add_21_2_g215(.A (add_21_2_n_6), .B (in1[9]), .S0
       (add_21_2_n_23), .Y (out1[9]));
  MXI2XL add_21_2_g216(.A (add_21_2_n_7), .B (in1[11]), .S0
       (add_21_2_n_22), .Y (out1[11]));
  MXI2XL add_21_2_g217(.A (add_21_2_n_4), .B (in1[10]), .S0
       (add_21_2_n_24), .Y (out1[10]));
  MXI2XL add_21_2_g218(.A (add_21_2_n_3), .B (in1[8]), .S0
       (add_21_2_n_46), .Y (out1[8]));
  NOR2X1 add_21_2_g219(.A (add_21_2_n_11), .B (add_21_2_n_47), .Y
       (add_21_2_n_24));
  NOR2X1 add_21_2_g220(.A (add_21_2_n_3), .B (add_21_2_n_47), .Y
       (add_21_2_n_23));
  NOR2X1 add_21_2_g221(.A (add_21_2_n_17), .B (add_21_2_n_47), .Y
       (add_21_2_n_22));
  MXI2XL add_21_2_g223(.A (add_21_2_n_8), .B (in1[7]), .S0
       (add_21_2_n_15), .Y (out1[7]));
  MXI2XL add_21_2_g224(.A (add_21_2_n_5), .B (in1[6]), .S0
       (add_21_2_n_16), .Y (out1[6]));
  NOR2X6 add_21_2_g226(.A (add_21_2_n_9), .B (add_21_2_n_14), .Y
       (add_21_2_n_18));
  OR2XL add_21_2_g227(.A (add_21_2_n_4), .B (add_21_2_n_11), .Y
       (add_21_2_n_17));
  NOR2BX1 add_21_2_g228(.AN (in1[3]), .B (add_21_2_n_12), .Y
       (add_21_2_n_16));
  NOR2X1 add_21_2_g229(.A (add_21_2_n_12), .B (add_21_2_n_10), .Y
       (add_21_2_n_15));
  NAND3X8 add_21_2_g230(.A (in1[5]), .B (in1[7]), .C (in1[6]), .Y
       (add_21_2_n_14));
  MXI2XL add_21_2_g231(.A (add_21_2_n_2), .B (in1[4]), .S0 (in1[3]), .Y
       (out1[4]));
  NAND2X1 add_21_2_g232(.A (in1[5]), .B (in1[4]), .Y (add_21_2_n_12));
  NAND2X1 add_21_2_g233(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_11));
  NAND2X1 add_21_2_g234(.A (in1[6]), .B (in1[3]), .Y (add_21_2_n_10));
  NAND2X2 add_21_2_g235(.A (in1[4]), .B (in1[3]), .Y (add_21_2_n_9));
  INVXL add_21_2_g236(.A (in1[7]), .Y (add_21_2_n_8));
  INVXL add_21_2_g237(.A (in1[11]), .Y (add_21_2_n_7));
  INVXL add_21_2_g238(.A (in1[9]), .Y (add_21_2_n_6));
  INVXL add_21_2_g239(.A (in1[6]), .Y (add_21_2_n_5));
  INVX1 add_21_2_g240(.A (in1[10]), .Y (add_21_2_n_4));
  INVX1 add_21_2_g241(.A (in1[8]), .Y (add_21_2_n_3));
  INVX1 add_21_2_g242(.A (in1[4]), .Y (add_21_2_n_2));
  XNOR2X1 add_21_2_g2(.A (in1[5]), .B (add_21_2_n_9), .Y (out1[5]));
  BUFX2 add_21_2_fopt(.A (add_21_2_n_18), .Y (add_21_2_n_46));
  CLKINVX3 add_21_2_fopt246(.A (add_21_2_n_18), .Y (add_21_2_n_47));
endmodule

