`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:47:21 CST (May  4 2021 16:47:21 UTC)

module DC_Filter_Add2i227Mul2i258Add2u1Mul2i3u2_1(in2, in1, out1);
  input [1:0] in2;
  input in1;
  output [11:0] out1;
  wire [1:0] in2;
  wire in1;
  wire [11:0] out1;
  wire asc001_7_, csa_tree_add_26_2_groupi_n_0,
       csa_tree_add_26_2_groupi_n_2, csa_tree_add_32_2_groupi_n_1,
       csa_tree_add_32_2_groupi_n_4, csa_tree_add_32_2_groupi_n_5,
       csa_tree_add_32_2_groupi_n_6, csa_tree_add_32_2_groupi_n_8;
  wire csa_tree_add_32_2_groupi_n_9, csa_tree_add_32_2_groupi_n_12,
       csa_tree_add_32_2_groupi_n_14, csa_tree_add_32_2_groupi_n_15,
       csa_tree_add_32_2_groupi_n_18, csa_tree_add_32_2_groupi_n_34,
       csa_tree_add_32_2_groupi_n_36, csa_tree_add_32_2_groupi_n_37;
  wire csa_tree_add_32_2_groupi_n_38, csa_tree_add_32_2_groupi_n_39,
       csa_tree_add_32_2_groupi_n_40, csa_tree_add_32_2_groupi_n_41,
       csa_tree_add_32_2_groupi_n_54, csa_tree_add_32_2_groupi_n_55,
       csa_tree_add_32_2_groupi_n_56, csa_tree_add_32_2_groupi_n_58;
  wire csa_tree_add_32_2_groupi_n_59, n_1, n_2, n_3, n_4;
  assign out1[0] = 1'b1;
  assign out1[5] = out1[7];
  assign out1[6] = out1[7];
  INVX1 g8(.A (n_1), .Y (out1[1]));
  BUFX3 fopt(.A (asc001_7_), .Y (out1[7]));
  ADDHX1 csa_tree_add_26_2_groupi_g81(.A (in2[1]), .B
       (csa_tree_add_26_2_groupi_n_2), .CO (n_4), .S (n_3));
  ADDFX1 csa_tree_add_26_2_groupi_g82(.A (in2[1]), .B (in2[0]), .CI
       (csa_tree_add_26_2_groupi_n_0), .CO
       (csa_tree_add_26_2_groupi_n_2), .S (n_2));
  ADDHX1 csa_tree_add_26_2_groupi_g83(.A (in2[0]), .B (in1), .CO
       (csa_tree_add_26_2_groupi_n_0), .S (n_1));
  MXI2XL csa_tree_add_32_2_groupi_g220(.A
       (csa_tree_add_32_2_groupi_n_37), .B
       (csa_tree_add_32_2_groupi_n_36), .S0
       (csa_tree_add_32_2_groupi_n_18), .Y (out1[9]));
  ADDHXL csa_tree_add_32_2_groupi_g221(.A (n_1), .B
       (csa_tree_add_32_2_groupi_n_12), .CO
       (csa_tree_add_32_2_groupi_n_18), .S (out1[8]));
  MXI2XL csa_tree_add_32_2_groupi_g222(.A
       (csa_tree_add_32_2_groupi_n_1), .B (n_4), .S0
       (csa_tree_add_32_2_groupi_n_14), .Y (out1[11]));
  MXI2XL csa_tree_add_32_2_groupi_g223(.A
       (csa_tree_add_32_2_groupi_n_56), .B
       (csa_tree_add_32_2_groupi_n_54), .S0
       (csa_tree_add_32_2_groupi_n_15), .Y (out1[10]));
  NOR2X1 csa_tree_add_32_2_groupi_g224(.A
       (csa_tree_add_32_2_groupi_n_6), .B (asc001_7_), .Y
       (csa_tree_add_32_2_groupi_n_15));
  NOR2X1 csa_tree_add_32_2_groupi_g225(.A
       (csa_tree_add_32_2_groupi_n_9), .B (asc001_7_), .Y
       (csa_tree_add_32_2_groupi_n_14));
  ADDHX1 csa_tree_add_32_2_groupi_g227(.A (n_4), .B
       (csa_tree_add_32_2_groupi_n_8), .CO
       (csa_tree_add_32_2_groupi_n_12), .S (out1[4]));
  MXI2XL csa_tree_add_32_2_groupi_g228(.A
       (csa_tree_add_32_2_groupi_n_55), .B
       (csa_tree_add_32_2_groupi_n_56), .S0
       (csa_tree_add_32_2_groupi_n_34), .Y (out1[3]));
  NAND2BX1 csa_tree_add_32_2_groupi_g229(.AN
       (csa_tree_add_32_2_groupi_n_6), .B
       (csa_tree_add_32_2_groupi_n_58), .Y
       (csa_tree_add_32_2_groupi_n_9));
  NOR2X2 csa_tree_add_32_2_groupi_g230(.A
       (csa_tree_add_32_2_groupi_n_5), .B
       (csa_tree_add_32_2_groupi_n_59), .Y
       (csa_tree_add_32_2_groupi_n_8));
  MXI2XL csa_tree_add_32_2_groupi_g231(.A
       (csa_tree_add_32_2_groupi_n_4), .B (n_1), .S0
       (csa_tree_add_32_2_groupi_n_38), .Y (out1[2]));
  NAND2X1 csa_tree_add_32_2_groupi_g232(.A
       (csa_tree_add_32_2_groupi_n_40), .B (n_1), .Y
       (csa_tree_add_32_2_groupi_n_6));
  NAND2BX1 csa_tree_add_32_2_groupi_g233(.AN
       (csa_tree_add_32_2_groupi_n_4), .B (n_2), .Y
       (csa_tree_add_32_2_groupi_n_5));
  INVX1 csa_tree_add_32_2_groupi_g234(.A (n_1), .Y
       (csa_tree_add_32_2_groupi_n_4));
  INVX1 csa_tree_add_32_2_groupi_g237(.A (n_4), .Y
       (csa_tree_add_32_2_groupi_n_1));
  CLKINVX1 csa_tree_add_32_2_groupi_fopt(.A
       (csa_tree_add_32_2_groupi_n_12), .Y (asc001_7_));
  BUFX2 csa_tree_add_32_2_groupi_fopt243(.A
       (csa_tree_add_32_2_groupi_n_5), .Y
       (csa_tree_add_32_2_groupi_n_34));
  INVXL csa_tree_add_32_2_groupi_fopt244(.A
       (csa_tree_add_32_2_groupi_n_37), .Y
       (csa_tree_add_32_2_groupi_n_36));
  INVXL csa_tree_add_32_2_groupi_fopt245(.A
       (csa_tree_add_32_2_groupi_n_39), .Y
       (csa_tree_add_32_2_groupi_n_37));
  BUFX2 csa_tree_add_32_2_groupi_fopt246(.A
       (csa_tree_add_32_2_groupi_n_39), .Y
       (csa_tree_add_32_2_groupi_n_38));
  INVXL csa_tree_add_32_2_groupi_fopt247(.A
       (csa_tree_add_32_2_groupi_n_41), .Y
       (csa_tree_add_32_2_groupi_n_39));
  INVXL csa_tree_add_32_2_groupi_fopt248(.A
       (csa_tree_add_32_2_groupi_n_41), .Y
       (csa_tree_add_32_2_groupi_n_40));
  INVXL csa_tree_add_32_2_groupi_fopt249(.A (n_2), .Y
       (csa_tree_add_32_2_groupi_n_41));
  INVXL csa_tree_add_32_2_groupi_fopt257(.A
       (csa_tree_add_32_2_groupi_n_56), .Y
       (csa_tree_add_32_2_groupi_n_54));
  INVXL csa_tree_add_32_2_groupi_fopt258(.A
       (csa_tree_add_32_2_groupi_n_56), .Y
       (csa_tree_add_32_2_groupi_n_55));
  CLKINVX1 csa_tree_add_32_2_groupi_fopt259(.A
       (csa_tree_add_32_2_groupi_n_58), .Y
       (csa_tree_add_32_2_groupi_n_56));
  CLKINVX1 csa_tree_add_32_2_groupi_fopt260(.A
       (csa_tree_add_32_2_groupi_n_59), .Y
       (csa_tree_add_32_2_groupi_n_58));
  CLKINVX2 csa_tree_add_32_2_groupi_fopt261(.A (n_3), .Y
       (csa_tree_add_32_2_groupi_n_59));
endmodule

