`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:47:19 CST (May  4 2021 16:47:19 UTC)

module DC_Filter_Add2i230Mul2i258Add2u1Mul2i3u2_1(in2, in1, out1);
  input [1:0] in2;
  input in1;
  output [11:0] out1;
  wire [1:0] in2;
  wire in1;
  wire [11:0] out1;
  wire asc001_7_, csa_tree_add_26_2_groupi_n_0,
       csa_tree_add_26_2_groupi_n_2, csa_tree_add_32_2_groupi_n_6,
       csa_tree_add_32_2_groupi_n_7, csa_tree_add_32_2_groupi_n_8,
       csa_tree_add_32_2_groupi_n_9, csa_tree_add_32_2_groupi_n_10;
  wire csa_tree_add_32_2_groupi_n_11, csa_tree_add_32_2_groupi_n_15,
       csa_tree_add_32_2_groupi_n_18, csa_tree_add_32_2_groupi_n_19,
       csa_tree_add_32_2_groupi_n_21, csa_tree_add_32_2_groupi_n_30,
       csa_tree_add_32_2_groupi_n_32, csa_tree_add_32_2_groupi_n_33;
  wire csa_tree_add_32_2_groupi_n_34, csa_tree_add_32_2_groupi_n_35,
       csa_tree_add_32_2_groupi_n_38, csa_tree_add_32_2_groupi_n_39,
       csa_tree_add_32_2_groupi_n_41, csa_tree_add_32_2_groupi_n_42,
       csa_tree_add_32_2_groupi_n_43, csa_tree_add_32_2_groupi_n_45;
  wire n_1, n_2, n_3, n_4;
  assign out1[0] = 1'b0;
  assign out1[5] = out1[7];
  assign out1[6] = out1[7];
  INVX1 g8(.A (n_1), .Y (out1[1]));
  BUFX3 fopt(.A (asc001_7_), .Y (out1[7]));
  MXI2X1 csa_tree_add_32_2_groupi_g222(.A
       (csa_tree_add_32_2_groupi_n_6), .B (n_4), .S0
       (csa_tree_add_32_2_groupi_n_21), .Y (out1[11]));
  MXI2XL csa_tree_add_32_2_groupi_g223(.A
       (csa_tree_add_32_2_groupi_n_43), .B
       (csa_tree_add_32_2_groupi_n_41), .S0
       (csa_tree_add_32_2_groupi_n_19), .Y (out1[10]));
  NOR3X2 csa_tree_add_32_2_groupi_g224(.A
       (csa_tree_add_32_2_groupi_n_45), .B
       (csa_tree_add_32_2_groupi_n_8), .C
       (csa_tree_add_32_2_groupi_n_39), .Y
       (csa_tree_add_32_2_groupi_n_21));
  MXI2XL csa_tree_add_32_2_groupi_g225(.A
       (csa_tree_add_32_2_groupi_n_7), .B (n_1), .S0
       (csa_tree_add_32_2_groupi_n_38), .Y (out1[8]));
  NOR2X1 csa_tree_add_32_2_groupi_g226(.A
       (csa_tree_add_32_2_groupi_n_8), .B
       (csa_tree_add_32_2_groupi_n_39), .Y
       (csa_tree_add_32_2_groupi_n_19));
  NAND2X2 csa_tree_add_32_2_groupi_g227(.A (n_1), .B
       (csa_tree_add_32_2_groupi_n_15), .Y
       (csa_tree_add_32_2_groupi_n_18));
  MXI2XL csa_tree_add_32_2_groupi_g229(.A
       (csa_tree_add_32_2_groupi_n_6), .B (n_4), .S0
       (csa_tree_add_32_2_groupi_n_30), .Y (out1[4]));
  NOR2X4 csa_tree_add_32_2_groupi_g230(.A
       (csa_tree_add_32_2_groupi_n_6), .B
       (csa_tree_add_32_2_groupi_n_11), .Y
       (csa_tree_add_32_2_groupi_n_15));
  MXI2XL csa_tree_add_32_2_groupi_g231(.A
       (csa_tree_add_32_2_groupi_n_41), .B
       (csa_tree_add_32_2_groupi_n_42), .S0
       (csa_tree_add_32_2_groupi_n_10), .Y (out1[3]));
  NAND2BX1 csa_tree_add_32_2_groupi_g232(.AN
       (csa_tree_add_32_2_groupi_n_10), .B
       (csa_tree_add_32_2_groupi_n_8), .Y (out1[2]));
  NAND2X2 csa_tree_add_32_2_groupi_g234(.A
       (csa_tree_add_32_2_groupi_n_9), .B (n_3), .Y
       (csa_tree_add_32_2_groupi_n_11));
  NOR2BX1 csa_tree_add_32_2_groupi_g235(.AN
       (csa_tree_add_32_2_groupi_n_7), .B
       (csa_tree_add_32_2_groupi_n_32), .Y
       (csa_tree_add_32_2_groupi_n_10));
  NAND2BX1 csa_tree_add_32_2_groupi_g236(.AN (n_2), .B
       (csa_tree_add_32_2_groupi_n_7), .Y
       (csa_tree_add_32_2_groupi_n_9));
  NAND2X1 csa_tree_add_32_2_groupi_g237(.A
       (csa_tree_add_32_2_groupi_n_34), .B (n_1), .Y
       (csa_tree_add_32_2_groupi_n_8));
  INVX1 csa_tree_add_32_2_groupi_g238(.A (n_1), .Y
       (csa_tree_add_32_2_groupi_n_7));
  INVX1 csa_tree_add_32_2_groupi_g240(.A (n_4), .Y
       (csa_tree_add_32_2_groupi_n_6));
  XNOR2X1 csa_tree_add_32_2_groupi_g2(.A
       (csa_tree_add_32_2_groupi_n_33), .B
       (csa_tree_add_32_2_groupi_n_18), .Y (out1[9]));
  INVXL csa_tree_add_32_2_groupi_fopt250(.A
       (csa_tree_add_32_2_groupi_n_11), .Y
       (csa_tree_add_32_2_groupi_n_30));
  BUFX2 csa_tree_add_32_2_groupi_fopt251(.A
       (csa_tree_add_32_2_groupi_n_33), .Y
       (csa_tree_add_32_2_groupi_n_32));
  INVXL csa_tree_add_32_2_groupi_fopt252(.A
       (csa_tree_add_32_2_groupi_n_35), .Y
       (csa_tree_add_32_2_groupi_n_33));
  INVXL csa_tree_add_32_2_groupi_fopt253(.A
       (csa_tree_add_32_2_groupi_n_35), .Y
       (csa_tree_add_32_2_groupi_n_34));
  INVXL csa_tree_add_32_2_groupi_fopt254(.A (n_2), .Y
       (csa_tree_add_32_2_groupi_n_35));
  INVXL csa_tree_add_32_2_groupi_fopt255(.A
       (csa_tree_add_32_2_groupi_n_38), .Y (asc001_7_));
  CLKINVX1 csa_tree_add_32_2_groupi_fopt256(.A
       (csa_tree_add_32_2_groupi_n_39), .Y
       (csa_tree_add_32_2_groupi_n_38));
  CLKINVX2 csa_tree_add_32_2_groupi_fopt257(.A
       (csa_tree_add_32_2_groupi_n_15), .Y
       (csa_tree_add_32_2_groupi_n_39));
  INVXL csa_tree_add_32_2_groupi_fopt258(.A
       (csa_tree_add_32_2_groupi_n_41), .Y
       (csa_tree_add_32_2_groupi_n_42));
  INVXL csa_tree_add_32_2_groupi_fopt259(.A
       (csa_tree_add_32_2_groupi_n_41), .Y
       (csa_tree_add_32_2_groupi_n_43));
  CLKINVX1 csa_tree_add_32_2_groupi_fopt260(.A
       (csa_tree_add_32_2_groupi_n_45), .Y
       (csa_tree_add_32_2_groupi_n_41));
  CLKINVX1 csa_tree_add_32_2_groupi_fopt261(.A (n_3), .Y
       (csa_tree_add_32_2_groupi_n_45));
  ADDHX1 csa_tree_add_26_2_groupi_g81(.A (in2[1]), .B
       (csa_tree_add_26_2_groupi_n_2), .CO (n_4), .S (n_3));
  ADDFX1 csa_tree_add_26_2_groupi_g82(.A (in2[1]), .B (in2[0]), .CI
       (csa_tree_add_26_2_groupi_n_0), .CO
       (csa_tree_add_26_2_groupi_n_2), .S (n_2));
  ADDHX1 csa_tree_add_26_2_groupi_g83(.A (in2[0]), .B (in1), .CO
       (csa_tree_add_26_2_groupi_n_0), .S (n_1));
endmodule

