`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:43:14 CST (May  4 2021 16:43:14 UTC)

module DC_Filter_Add_12U_289_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_4, add_21_2_n_6, add_21_2_n_7, add_21_2_n_8,
       add_21_2_n_9, add_21_2_n_10, add_21_2_n_11, add_21_2_n_12;
  wire add_21_2_n_13, add_21_2_n_14, add_21_2_n_15, add_21_2_n_16,
       add_21_2_n_17, add_21_2_n_18, add_21_2_n_19, add_21_2_n_21;
  wire add_21_2_n_22, add_21_2_n_23, add_21_2_n_25, add_21_2_n_26,
       add_21_2_n_29, add_21_2_n_51, add_21_2_n_52, add_21_2_n_53;
  wire add_21_2_n_59;
  assign out1[0] = in1[0];
  INVX1 g7(.A (in1[1]), .Y (out1[1]));
  MXI2X1 add_21_2_g203(.A (add_21_2_n_8), .B (in1[9]), .S0
       (add_21_2_n_29), .Y (out1[9]));
  ADDHX1 add_21_2_g204(.A (in1[8]), .B (add_21_2_n_21), .CO
       (add_21_2_n_29), .S (out1[8]));
  NAND2BX1 add_21_2_g205(.AN (add_21_2_n_26), .B (add_21_2_n_25), .Y
       (out1[5]));
  MXI2X1 add_21_2_g207(.A (add_21_2_n_9), .B (in1[10]), .S0
       (add_21_2_n_4), .Y (out1[10]));
  NOR2X1 add_21_2_g208(.A (in1[5]), .B (add_21_2_n_19), .Y
       (add_21_2_n_26));
  NAND2XL add_21_2_g209(.A (in1[5]), .B (add_21_2_n_19), .Y
       (add_21_2_n_25));
  MXI2XL add_21_2_g210(.A (add_21_2_n_7), .B (in1[7]), .S0
       (add_21_2_n_22), .Y (out1[7]));
  NAND2X1 add_21_2_g212(.A (add_21_2_n_17), .B (add_21_2_n_21), .Y
       (add_21_2_n_23));
  NOR2BX1 add_21_2_g214(.AN (add_21_2_n_10), .B (add_21_2_n_18), .Y
       (add_21_2_n_22));
  OAI21X2 add_21_2_g216(.A0 (add_21_2_n_13), .A1 (add_21_2_n_15), .B0
       (add_21_2_n_16), .Y (add_21_2_n_21));
  MXI2XL add_21_2_g217(.A (in1[4]), .B (add_21_2_n_6), .S0
       (add_21_2_n_51), .Y (out1[4]));
  NOR2X1 add_21_2_g218(.A (add_21_2_n_6), .B (add_21_2_n_15), .Y
       (add_21_2_n_19));
  NOR2X1 add_21_2_g219(.A (add_21_2_n_59), .B (add_21_2_n_52), .Y
       (add_21_2_n_18));
  NOR2X1 add_21_2_g220(.A (add_21_2_n_9), .B (add_21_2_n_11), .Y
       (add_21_2_n_17));
  AOI21X2 add_21_2_g221(.A0 (in1[6]), .A1 (in1[5]), .B0 (in1[7]), .Y
       (add_21_2_n_16));
  NOR3X8 add_21_2_g222(.A (in1[1]), .B (in1[3]), .C (in1[2]), .Y
       (add_21_2_n_15));
  NOR2X2 add_21_2_g225(.A (in1[2]), .B (in1[1]), .Y (add_21_2_n_14));
  NAND2X4 add_21_2_g226(.A (in1[6]), .B (in1[4]), .Y (add_21_2_n_13));
  NAND2X1 add_21_2_g227(.A (in1[2]), .B (in1[1]), .Y (add_21_2_n_12));
  NAND2X1 add_21_2_g228(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_11));
  NAND2X1 add_21_2_g229(.A (in1[6]), .B (in1[5]), .Y (add_21_2_n_10));
  INVX1 add_21_2_g231(.A (in1[10]), .Y (add_21_2_n_9));
  INVX1 add_21_2_g233(.A (in1[9]), .Y (add_21_2_n_8));
  INVXL add_21_2_g234(.A (in1[7]), .Y (add_21_2_n_7));
  INVX1 add_21_2_g235(.A (in1[4]), .Y (add_21_2_n_6));
  NOR2BX1 add_21_2_g2(.AN (add_21_2_n_21), .B (add_21_2_n_11), .Y
       (add_21_2_n_4));
  NAND2BX1 add_21_2_g237(.AN (add_21_2_n_14), .B (add_21_2_n_12), .Y
       (out1[2]));
  XNOR2XL add_21_2_g238(.A (in1[11]), .B (add_21_2_n_23), .Y
       (out1[11]));
  CLKXOR2X1 add_21_2_g239(.A (in1[3]), .B (add_21_2_n_14), .Y
       (out1[3]));
  XNOR2X1 add_21_2_g240(.A (in1[6]), .B (add_21_2_n_26), .Y (out1[6]));
  INVXL add_21_2_fopt(.A (add_21_2_n_53), .Y (add_21_2_n_51));
  INVXL add_21_2_fopt241(.A (add_21_2_n_53), .Y (add_21_2_n_52));
  INVXL add_21_2_fopt242(.A (add_21_2_n_15), .Y (add_21_2_n_53));
  BUFX2 add_21_2_fopt246(.A (add_21_2_n_13), .Y (add_21_2_n_59));
endmodule

