`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:45:30 CST (May  4 2021 16:45:30 UTC)

module DC_Filter_Add2i246Mul2i258Add3i1u1Mul2i3u2_1(in2, in1, out1);
  input [1:0] in2;
  input in1;
  output [11:0] out1;
  wire [1:0] in2;
  wire in1;
  wire [11:0] out1;
  wire csa_tree_add_29_2_groupi_n_0, csa_tree_add_29_2_groupi_n_1,
       csa_tree_add_29_2_groupi_n_3, csa_tree_add_29_2_groupi_n_5,
       csa_tree_add_29_2_groupi_n_12, csa_tree_add_29_2_groupi_n_23,
       csa_tree_add_35_2_groupi_n_0, csa_tree_add_35_2_groupi_n_1;
  wire csa_tree_add_35_2_groupi_n_5, csa_tree_add_35_2_groupi_n_6,
       csa_tree_add_35_2_groupi_n_7, csa_tree_add_35_2_groupi_n_8,
       csa_tree_add_35_2_groupi_n_9, csa_tree_add_35_2_groupi_n_12,
       csa_tree_add_35_2_groupi_n_13, csa_tree_add_35_2_groupi_n_15;
  wire csa_tree_add_35_2_groupi_n_17, csa_tree_add_35_2_groupi_n_18,
       csa_tree_add_35_2_groupi_n_21, csa_tree_add_35_2_groupi_n_28,
       csa_tree_add_35_2_groupi_n_29, csa_tree_add_35_2_groupi_n_30,
       csa_tree_add_35_2_groupi_n_31, csa_tree_add_35_2_groupi_n_32;
  wire csa_tree_add_35_2_groupi_n_35, csa_tree_add_35_2_groupi_n_36,
       n_1, n_2, n_3, n_4;
  assign out1[0] = 1'b0;
  assign out1[5] = out1[7];
  assign out1[6] = out1[7];
  INVX1 g10(.A (n_1), .Y (out1[1]));
  ADDHX1 csa_tree_add_29_2_groupi_g86(.A (in2[1]), .B
       (csa_tree_add_29_2_groupi_n_5), .CO (n_4), .S (n_3));
  ADDFHXL csa_tree_add_29_2_groupi_g87(.A (in2[1]), .B (in2[0]), .CI
       (csa_tree_add_29_2_groupi_n_0), .CO
       (csa_tree_add_29_2_groupi_n_5), .S (n_2));
  NAND2X2 csa_tree_add_29_2_groupi_g88(.A
       (csa_tree_add_29_2_groupi_n_3), .B
       (csa_tree_add_29_2_groupi_n_12), .Y (n_1));
  NAND2X1 csa_tree_add_29_2_groupi_g90(.A (in2[0]), .B (in1), .Y
       (csa_tree_add_29_2_groupi_n_3));
  CLKINVX3 csa_tree_add_29_2_groupi_g93(.A (in1), .Y
       (csa_tree_add_29_2_groupi_n_1));
  NAND2X4 csa_tree_add_29_2_groupi_g94(.A
       (csa_tree_add_29_2_groupi_n_23), .B
       (csa_tree_add_29_2_groupi_n_1), .Y
       (csa_tree_add_29_2_groupi_n_0));
  BUFX3 csa_tree_add_29_2_groupi_fopt(.A
       (csa_tree_add_29_2_groupi_n_0), .Y
       (csa_tree_add_29_2_groupi_n_12));
  CLKINVX6 csa_tree_add_29_2_groupi_fopt101(.A (in2[0]), .Y
       (csa_tree_add_29_2_groupi_n_23));
  MXI2XL csa_tree_add_35_2_groupi_g231(.A
       (csa_tree_add_35_2_groupi_n_29), .B
       (csa_tree_add_35_2_groupi_n_28), .S0
       (csa_tree_add_35_2_groupi_n_21), .Y (out1[9]));
  ADDHXL csa_tree_add_35_2_groupi_g232(.A (n_1), .B
       (csa_tree_add_35_2_groupi_n_13), .CO
       (csa_tree_add_35_2_groupi_n_21), .S (out1[8]));
  MXI2XL csa_tree_add_35_2_groupi_g233(.A
       (csa_tree_add_35_2_groupi_n_5), .B (n_4), .S0
       (csa_tree_add_35_2_groupi_n_17), .Y (out1[11]));
  MXI2XL csa_tree_add_35_2_groupi_g234(.A
       (csa_tree_add_35_2_groupi_n_6), .B (n_3), .S0
       (csa_tree_add_35_2_groupi_n_18), .Y (out1[10]));
  NOR2X1 csa_tree_add_35_2_groupi_g235(.A
       (csa_tree_add_35_2_groupi_n_7), .B
       (csa_tree_add_35_2_groupi_n_36), .Y
       (csa_tree_add_35_2_groupi_n_18));
  NOR2X1 csa_tree_add_35_2_groupi_g236(.A
       (csa_tree_add_35_2_groupi_n_15), .B
       (csa_tree_add_35_2_groupi_n_36), .Y
       (csa_tree_add_35_2_groupi_n_17));
  OR2XL csa_tree_add_35_2_groupi_g238(.A
       (csa_tree_add_35_2_groupi_n_6), .B
       (csa_tree_add_35_2_groupi_n_7), .Y
       (csa_tree_add_35_2_groupi_n_15));
  NAND2BX1 csa_tree_add_35_2_groupi_g239(.AN
       (csa_tree_add_35_2_groupi_n_12), .B
       (csa_tree_add_35_2_groupi_n_35), .Y (out1[4]));
  NAND2X4 csa_tree_add_35_2_groupi_g240(.A
       (csa_tree_add_35_2_groupi_n_5), .B
       (csa_tree_add_35_2_groupi_n_9), .Y
       (csa_tree_add_35_2_groupi_n_13));
  NOR2XL csa_tree_add_35_2_groupi_g241(.A
       (csa_tree_add_35_2_groupi_n_5), .B
       (csa_tree_add_35_2_groupi_n_9), .Y
       (csa_tree_add_35_2_groupi_n_12));
  MXI2X1 csa_tree_add_35_2_groupi_g242(.A (n_3), .B
       (csa_tree_add_35_2_groupi_n_6), .S0
       (csa_tree_add_35_2_groupi_n_1), .Y (out1[3]));
  NAND2BX1 csa_tree_add_35_2_groupi_g243(.AN
       (csa_tree_add_35_2_groupi_n_8), .B
       (csa_tree_add_35_2_groupi_n_7), .Y (out1[2]));
  NAND2X2 csa_tree_add_35_2_groupi_g244(.A (n_3), .B
       (csa_tree_add_35_2_groupi_n_0), .Y
       (csa_tree_add_35_2_groupi_n_9));
  NOR2XL csa_tree_add_35_2_groupi_g245(.A
       (csa_tree_add_35_2_groupi_n_30), .B (n_1), .Y
       (csa_tree_add_35_2_groupi_n_8));
  NAND2X1 csa_tree_add_35_2_groupi_g246(.A (n_2), .B (n_1), .Y
       (csa_tree_add_35_2_groupi_n_7));
  INVX1 csa_tree_add_35_2_groupi_g250(.A (n_3), .Y
       (csa_tree_add_35_2_groupi_n_6));
  INVX1 csa_tree_add_35_2_groupi_g252(.A (n_4), .Y
       (csa_tree_add_35_2_groupi_n_5));
  NOR2X1 csa_tree_add_35_2_groupi_g2(.A (n_1), .B
       (csa_tree_add_35_2_groupi_n_31), .Y
       (csa_tree_add_35_2_groupi_n_1));
  OR2X1 csa_tree_add_35_2_groupi_g255(.A (n_1), .B (n_2), .Y
       (csa_tree_add_35_2_groupi_n_0));
  INVXL csa_tree_add_35_2_groupi_fopt(.A
       (csa_tree_add_35_2_groupi_n_29), .Y
       (csa_tree_add_35_2_groupi_n_28));
  INVXL csa_tree_add_35_2_groupi_fopt256(.A
       (csa_tree_add_35_2_groupi_n_30), .Y
       (csa_tree_add_35_2_groupi_n_29));
  INVXL csa_tree_add_35_2_groupi_fopt257(.A
       (csa_tree_add_35_2_groupi_n_32), .Y
       (csa_tree_add_35_2_groupi_n_30));
  INVXL csa_tree_add_35_2_groupi_fopt258(.A
       (csa_tree_add_35_2_groupi_n_32), .Y
       (csa_tree_add_35_2_groupi_n_31));
  INVXL csa_tree_add_35_2_groupi_fopt259(.A (n_2), .Y
       (csa_tree_add_35_2_groupi_n_32));
  CLKINVX2 csa_tree_add_35_2_groupi_fopt260(.A
       (csa_tree_add_35_2_groupi_n_35), .Y (out1[7]));
  CLKINVX1 csa_tree_add_35_2_groupi_fopt261(.A
       (csa_tree_add_35_2_groupi_n_36), .Y
       (csa_tree_add_35_2_groupi_n_35));
  CLKINVX2 csa_tree_add_35_2_groupi_fopt262(.A
       (csa_tree_add_35_2_groupi_n_13), .Y
       (csa_tree_add_35_2_groupi_n_36));
endmodule

