`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:42:46 CST (May  4 2021 16:42:46 UTC)

module DC_Filter_Add_12U_247_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_0, add_21_2_n_1, add_21_2_n_3, add_21_2_n_4,
       add_21_2_n_5, add_21_2_n_6, add_21_2_n_7, add_21_2_n_8;
  wire add_21_2_n_9, add_21_2_n_10, add_21_2_n_11, add_21_2_n_12,
       add_21_2_n_13, add_21_2_n_15, add_21_2_n_16, add_21_2_n_17;
  wire add_21_2_n_18, add_21_2_n_19, add_21_2_n_21, add_21_2_n_25,
       add_21_2_n_26, add_21_2_n_27;
  assign out1[0] = in1[0];
  assign out1[1] = in1[1];
  INVX1 g7(.A (in1[2]), .Y (out1[2]));
  MXI2XL add_21_2_g201(.A (add_21_2_n_4), .B (in1[9]), .S0
       (add_21_2_n_26), .Y (out1[9]));
  MXI2XL add_21_2_g202(.A (add_21_2_n_7), .B (in1[11]), .S0
       (add_21_2_n_25), .Y (out1[11]));
  MXI2XL add_21_2_g203(.A (add_21_2_n_10), .B (in1[10]), .S0
       (add_21_2_n_27), .Y (out1[10]));
  MXI2XL add_21_2_g204(.A (add_21_2_n_9), .B (in1[8]), .S0
       (add_21_2_n_1), .Y (out1[8]));
  NOR2X1 add_21_2_g205(.A (add_21_2_n_13), .B (add_21_2_n_21), .Y
       (add_21_2_n_27));
  NOR2X1 add_21_2_g206(.A (add_21_2_n_9), .B (add_21_2_n_21), .Y
       (add_21_2_n_26));
  NOR2X1 add_21_2_g207(.A (add_21_2_n_15), .B (add_21_2_n_21), .Y
       (add_21_2_n_25));
  MXI2XL add_21_2_g208(.A (add_21_2_n_5), .B (in1[5]), .S0
       (add_21_2_n_18), .Y (out1[5]));
  NAND2BX1 add_21_2_g210(.AN (add_21_2_n_0), .B (add_21_2_n_1), .Y
       (out1[7]));
  MXI2XL add_21_2_g211(.A (add_21_2_n_6), .B (in1[6]), .S0
       (add_21_2_n_19), .Y (out1[6]));
  INVX1 add_21_2_g213(.A (add_21_2_n_21), .Y (add_21_2_n_1));
  NOR2X4 add_21_2_g214(.A (in1[7]), .B (add_21_2_n_17), .Y
       (add_21_2_n_21));
  MXI2XL add_21_2_g215(.A (in1[4]), .B (add_21_2_n_3), .S0
       (add_21_2_n_11), .Y (out1[4]));
  NOR2X1 add_21_2_g216(.A (add_21_2_n_12), .B (add_21_2_n_11), .Y
       (add_21_2_n_19));
  NOR2X1 add_21_2_g217(.A (add_21_2_n_3), .B (add_21_2_n_11), .Y
       (add_21_2_n_18));
  NOR2X6 add_21_2_g219(.A (add_21_2_n_11), .B (add_21_2_n_16), .Y
       (add_21_2_n_17));
  NAND3X8 add_21_2_g220(.A (in1[6]), .B (in1[5]), .C (in1[4]), .Y
       (add_21_2_n_16));
  OR2XL add_21_2_g221(.A (add_21_2_n_10), .B (add_21_2_n_13), .Y
       (add_21_2_n_15));
  MXI2XL add_21_2_g222(.A (add_21_2_n_8), .B (in1[3]), .S0 (in1[2]), .Y
       (out1[3]));
  NAND2X1 add_21_2_g223(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_13));
  NAND2X1 add_21_2_g224(.A (in1[5]), .B (in1[4]), .Y (add_21_2_n_12));
  NAND2X4 add_21_2_g225(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_11));
  INVX1 add_21_2_g226(.A (in1[10]), .Y (add_21_2_n_10));
  INVX1 add_21_2_g227(.A (in1[8]), .Y (add_21_2_n_9));
  INVX1 add_21_2_g228(.A (in1[3]), .Y (add_21_2_n_8));
  INVXL add_21_2_g229(.A (in1[11]), .Y (add_21_2_n_7));
  INVXL add_21_2_g230(.A (in1[6]), .Y (add_21_2_n_6));
  INVXL add_21_2_g231(.A (in1[5]), .Y (add_21_2_n_5));
  INVXL add_21_2_g232(.A (in1[9]), .Y (add_21_2_n_4));
  INVX1 add_21_2_g233(.A (in1[4]), .Y (add_21_2_n_3));
  AND2XL add_21_2_g2(.A (in1[7]), .B (add_21_2_n_17), .Y
       (add_21_2_n_0));
endmodule

