`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:41:58 CST (May  4 2021 16:41:58 UTC)

module DC_Filter_Add_12U_175_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_1, add_21_2_n_2, add_21_2_n_3, add_21_2_n_4,
       add_21_2_n_5, add_21_2_n_6, add_21_2_n_7, add_21_2_n_8;
  wire add_21_2_n_9, add_21_2_n_10, add_21_2_n_11, add_21_2_n_12,
       add_21_2_n_13, add_21_2_n_14, add_21_2_n_15, add_21_2_n_16;
  wire add_21_2_n_18, add_21_2_n_19, add_21_2_n_20, add_21_2_n_21,
       add_21_2_n_22, add_21_2_n_24, add_21_2_n_25, add_21_2_n_26;
  wire add_21_2_n_27, add_21_2_n_30, add_21_2_n_31, add_21_2_n_32,
       add_21_2_n_57, add_21_2_n_58, add_21_2_n_59, add_21_2_n_66;
  wire add_21_2_n_67, add_21_2_n_68;
  INVX1 g7(.A (in1[0]), .Y (out1[0]));
  MXI2X1 add_21_2_g218(.A (add_21_2_n_5), .B (in1[9]), .S0
       (add_21_2_n_31), .Y (out1[9]));
  MXI2X1 add_21_2_g219(.A (add_21_2_n_8), .B (in1[11]), .S0
       (add_21_2_n_30), .Y (out1[11]));
  MXI2XL add_21_2_g220(.A (add_21_2_n_4), .B (in1[5]), .S0
       (add_21_2_n_25), .Y (out1[5]));
  MXI2X1 add_21_2_g221(.A (add_21_2_n_10), .B (in1[10]), .S0
       (add_21_2_n_32), .Y (out1[10]));
  MXI2XL add_21_2_g223(.A (in1[8]), .B (add_21_2_n_9), .S0
       (add_21_2_n_27), .Y (out1[8]));
  MXI2XL add_21_2_g224(.A (in1[3]), .B (add_21_2_n_7), .S0
       (add_21_2_n_1), .Y (out1[3]));
  NOR2X1 add_21_2_g225(.A (add_21_2_n_14), .B (add_21_2_n_27), .Y
       (add_21_2_n_32));
  NOR2X1 add_21_2_g226(.A (add_21_2_n_9), .B (add_21_2_n_27), .Y
       (add_21_2_n_31));
  NOR2X1 add_21_2_g227(.A (add_21_2_n_20), .B (add_21_2_n_27), .Y
       (add_21_2_n_30));
  MXI2XL add_21_2_g228(.A (in1[6]), .B (add_21_2_n_3), .S0
       (add_21_2_n_2), .Y (out1[6]));
  NAND2BX1 add_21_2_g229(.AN (add_21_2_n_25), .B (add_21_2_n_24), .Y
       (out1[4]));
  AOI21X2 add_21_2_g230(.A0 (add_21_2_n_13), .A1 (add_21_2_n_21), .B0
       (add_21_2_n_18), .Y (add_21_2_n_27));
  AOI21X1 add_21_2_g231(.A0 (in1[6]), .A1 (add_21_2_n_21), .B0
       (add_21_2_n_19), .Y (add_21_2_n_26));
  NOR2X1 add_21_2_g233(.A (in1[4]), .B (add_21_2_n_58), .Y
       (add_21_2_n_25));
  NAND2X1 add_21_2_g234(.A (in1[4]), .B (add_21_2_n_57), .Y
       (add_21_2_n_24));
  NAND2BX1 add_21_2_g235(.AN (add_21_2_n_22), .B (add_21_2_n_1), .Y
       (out1[2]));
  NOR2BX1 add_21_2_g236(.AN (in1[2]), .B (add_21_2_n_66), .Y
       (add_21_2_n_22));
  NAND2X4 add_21_2_g238(.A (add_21_2_n_11), .B (add_21_2_n_16), .Y
       (add_21_2_n_21));
  OR2XL add_21_2_g239(.A (add_21_2_n_10), .B (add_21_2_n_14), .Y
       (add_21_2_n_20));
  NOR2X1 add_21_2_g240(.A (add_21_2_n_3), .B (add_21_2_n_15), .Y
       (add_21_2_n_19));
  NOR2X1 add_21_2_g241(.A (add_21_2_n_12), .B (add_21_2_n_15), .Y
       (add_21_2_n_18));
  MXI2XL add_21_2_g242(.A (add_21_2_n_6), .B (in1[1]), .S0 (in1[0]), .Y
       (out1[1]));
  NOR2X4 add_21_2_g243(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_16));
  NOR2X1 add_21_2_g245(.A (in1[5]), .B (in1[4]), .Y (add_21_2_n_15));
  NAND2X1 add_21_2_g246(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_14));
  CLKINVX2 add_21_2_g247(.A (add_21_2_n_12), .Y (add_21_2_n_13));
  NAND2X8 add_21_2_g248(.A (in1[7]), .B (in1[6]), .Y (add_21_2_n_12));
  NAND2X8 add_21_2_g249(.A (in1[1]), .B (in1[0]), .Y (add_21_2_n_11));
  INVX1 add_21_2_g250(.A (in1[10]), .Y (add_21_2_n_10));
  INVX1 add_21_2_g253(.A (in1[8]), .Y (add_21_2_n_9));
  INVXL add_21_2_g254(.A (in1[11]), .Y (add_21_2_n_8));
  INVX1 add_21_2_g255(.A (in1[3]), .Y (add_21_2_n_7));
  INVX1 add_21_2_g256(.A (in1[1]), .Y (add_21_2_n_6));
  INVXL add_21_2_g257(.A (in1[9]), .Y (add_21_2_n_5));
  INVXL add_21_2_g258(.A (in1[5]), .Y (add_21_2_n_4));
  INVX1 add_21_2_g259(.A (in1[6]), .Y (add_21_2_n_3));
  NOR2BX1 add_21_2_g2(.AN (add_21_2_n_15), .B (add_21_2_n_57), .Y
       (add_21_2_n_2));
  NAND2BX1 add_21_2_g260(.AN (in1[2]), .B (add_21_2_n_67), .Y
       (add_21_2_n_1));
  XNOR2XL add_21_2_g261(.A (in1[7]), .B (add_21_2_n_26), .Y (out1[7]));
  CLKINVX1 add_21_2_fopt(.A (add_21_2_n_59), .Y (add_21_2_n_57));
  CLKINVX1 add_21_2_fopt262(.A (add_21_2_n_59), .Y (add_21_2_n_58));
  CLKINVX1 add_21_2_fopt263(.A (add_21_2_n_21), .Y (add_21_2_n_59));
  INVXL add_21_2_fopt267(.A (add_21_2_n_68), .Y (add_21_2_n_66));
  INVXL add_21_2_fopt268(.A (add_21_2_n_68), .Y (add_21_2_n_67));
  INVXL add_21_2_fopt269(.A (add_21_2_n_11), .Y (add_21_2_n_68));
endmodule

