`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:41:19 CST (May  4 2021 16:41:19 UTC)

module DC_Filter_Add_12U_80_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_1, add_21_2_n_2, add_21_2_n_3, add_21_2_n_4,
       add_21_2_n_5, add_21_2_n_6, add_21_2_n_7, add_21_2_n_8;
  wire add_21_2_n_9, add_21_2_n_10, add_21_2_n_11, add_21_2_n_12,
       add_21_2_n_13, add_21_2_n_14, add_21_2_n_16, add_21_2_n_17;
  wire add_21_2_n_18, add_21_2_n_19, add_21_2_n_20, add_21_2_n_21,
       add_21_2_n_22, add_21_2_n_23, add_21_2_n_25, add_21_2_n_26;
  wire add_21_2_n_27, add_21_2_n_29, add_21_2_n_33;
  INVX1 g7(.A (in1[0]), .Y (out1[0]));
  MXI2XL add_21_2_g212(.A (add_21_2_n_8), .B (in1[9]), .S0
       (add_21_2_n_29), .Y (out1[9]));
  MXI2XL add_21_2_g213(.A (add_21_2_n_5), .B (in1[5]), .S0
       (add_21_2_n_27), .Y (out1[5]));
  OAI31X1 add_21_2_g214(.A0 (in1[11]), .A1 (add_21_2_n_18), .A2
       (add_21_2_n_25), .B0 (add_21_2_n_33), .Y (out1[11]));
  MXI2XL add_21_2_g215(.A (add_21_2_n_9), .B (in1[3]), .S0
       (add_21_2_n_22), .Y (out1[3]));
  OAI21X1 add_21_2_g217(.A0 (add_21_2_n_25), .A1 (add_21_2_n_18), .B0
       (in1[11]), .Y (add_21_2_n_33));
  MXI2XL add_21_2_g218(.A (in1[8]), .B (add_21_2_n_3), .S0
       (add_21_2_n_25), .Y (out1[8]));
  MXI2XL add_21_2_g219(.A (add_21_2_n_6), .B (in1[6]), .S0
       (add_21_2_n_2), .Y (out1[6]));
  MXI2XL add_21_2_g220(.A (add_21_2_n_4), .B (in1[7]), .S0
       (add_21_2_n_23), .Y (out1[7]));
  NOR2X1 add_21_2_g221(.A (add_21_2_n_3), .B (add_21_2_n_25), .Y
       (add_21_2_n_29));
  NAND2BXL add_21_2_g223(.AN (add_21_2_n_27), .B (add_21_2_n_26), .Y
       (out1[4]));
  NOR2X1 add_21_2_g225(.A (in1[4]), .B (add_21_2_n_20), .Y
       (add_21_2_n_27));
  NAND2XL add_21_2_g226(.A (in1[4]), .B (add_21_2_n_20), .Y
       (add_21_2_n_26));
  NOR2X6 add_21_2_g227(.A (add_21_2_n_16), .B (add_21_2_n_20), .Y
       (add_21_2_n_25));
  NAND2BXL add_21_2_g228(.AN (add_21_2_n_22), .B (add_21_2_n_21), .Y
       (out1[2]));
  NOR2X1 add_21_2_g229(.A (add_21_2_n_17), .B (add_21_2_n_20), .Y
       (add_21_2_n_23));
  NOR2X1 add_21_2_g230(.A (in1[2]), .B (add_21_2_n_19), .Y
       (add_21_2_n_22));
  NAND2X1 add_21_2_g231(.A (in1[2]), .B (add_21_2_n_19), .Y
       (add_21_2_n_21));
  NAND2X6 add_21_2_g232(.A (add_21_2_n_13), .B (add_21_2_n_12), .Y
       (add_21_2_n_20));
  INVX1 add_21_2_g233(.A (add_21_2_n_12), .Y (add_21_2_n_19));
  NAND2X1 add_21_2_g234(.A (in1[10]), .B (add_21_2_n_10), .Y
       (add_21_2_n_18));
  NAND2X1 add_21_2_g235(.A (add_21_2_n_6), .B (add_21_2_n_14), .Y
       (add_21_2_n_17));
  NAND2X6 add_21_2_g236(.A (add_21_2_n_14), .B (add_21_2_n_11), .Y
       (add_21_2_n_16));
  MXI2XL add_21_2_g237(.A (in1[1]), .B (add_21_2_n_7), .S0 (in1[0]), .Y
       (out1[1]));
  NOR2X8 add_21_2_g239(.A (in1[5]), .B (in1[4]), .Y (add_21_2_n_14));
  NOR2X6 add_21_2_g240(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_13));
  NOR2X6 add_21_2_g241(.A (in1[1]), .B (in1[0]), .Y (add_21_2_n_12));
  NOR2X4 add_21_2_g242(.A (in1[7]), .B (in1[6]), .Y (add_21_2_n_11));
  NOR2X2 add_21_2_g244(.A (add_21_2_n_8), .B (add_21_2_n_3), .Y
       (add_21_2_n_10));
  INVXL add_21_2_g245(.A (in1[3]), .Y (add_21_2_n_9));
  CLKINVX2 add_21_2_g246(.A (in1[9]), .Y (add_21_2_n_8));
  INVX1 add_21_2_g247(.A (in1[1]), .Y (add_21_2_n_7));
  INVX1 add_21_2_g249(.A (in1[6]), .Y (add_21_2_n_6));
  INVXL add_21_2_g250(.A (in1[5]), .Y (add_21_2_n_5));
  INVXL add_21_2_g251(.A (in1[7]), .Y (add_21_2_n_4));
  CLKINVX2 add_21_2_g252(.A (in1[8]), .Y (add_21_2_n_3));
  NOR2BX1 add_21_2_g2(.AN (add_21_2_n_14), .B (add_21_2_n_20), .Y
       (add_21_2_n_2));
  NOR2BX2 add_21_2_g253(.AN (add_21_2_n_10), .B (add_21_2_n_25), .Y
       (add_21_2_n_1));
  CLKXOR2X1 add_21_2_g254(.A (in1[10]), .B (add_21_2_n_1), .Y
       (out1[10]));
endmodule

