`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:42:37 CST (May  4 2021 16:42:37 UTC)

module DC_Filter_Add_12U_232_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_2, add_21_2_n_5, add_21_2_n_6, add_21_2_n_8,
       add_21_2_n_10, add_21_2_n_11, add_21_2_n_12, add_21_2_n_13;
  wire add_21_2_n_14, add_21_2_n_15, add_21_2_n_16, add_21_2_n_17,
       add_21_2_n_18, add_21_2_n_19, add_21_2_n_20, add_21_2_n_21;
  wire add_21_2_n_22, add_21_2_n_23, add_21_2_n_25, add_21_2_n_27,
       add_21_2_n_28, add_21_2_n_29, add_21_2_n_30, add_21_2_n_35;
  wire add_21_2_n_36, add_21_2_n_37, add_21_2_n_64, add_21_2_n_65,
       add_21_2_n_66, add_21_2_n_68, add_21_2_n_69, add_21_2_n_70;
  wire add_21_2_n_71, add_21_2_n_73, add_21_2_n_74, add_21_2_n_75,
       add_21_2_n_82, add_21_2_n_83, add_21_2_n_84, add_21_2_n_85;
  wire add_21_2_n_86, add_21_2_n_89, add_21_2_n_90, add_21_2_n_91,
       add_21_2_n_92, add_21_2_n_93, add_21_2_n_94, add_21_2_n_97;
  wire add_21_2_n_98, add_21_2_n_99, add_21_2_n_100, add_21_2_n_101;
  INVX1 g7(.A (in1[0]), .Y (out1[0]));
  MXI2X1 add_21_2_g217(.A (add_21_2_n_6), .B (in1[9]), .S0
       (add_21_2_n_36), .Y (out1[9]));
  MXI2X1 add_21_2_g218(.A (add_21_2_n_11), .B (in1[11]), .S0
       (add_21_2_n_35), .Y (out1[11]));
  MXI2X1 add_21_2_g220(.A (add_21_2_n_10), .B (in1[10]), .S0
       (add_21_2_n_37), .Y (out1[10]));
  MXI2X1 add_21_2_g221(.A (add_21_2_n_5), .B (in1[8]), .S0
       (add_21_2_n_89), .Y (out1[8]));
  NOR2X1 add_21_2_g222(.A (add_21_2_n_13), .B (add_21_2_n_90), .Y
       (add_21_2_n_37));
  NOR2X1 add_21_2_g223(.A (add_21_2_n_5), .B (add_21_2_n_90), .Y
       (add_21_2_n_36));
  NOR2X1 add_21_2_g224(.A (add_21_2_n_17), .B (add_21_2_n_90), .Y
       (add_21_2_n_35));
  MXI2XL add_21_2_g225(.A (add_21_2_n_83), .B (add_21_2_n_82), .S0
       (add_21_2_n_2), .Y (out1[6]));
  MXI2XL add_21_2_g226(.A (add_21_2_n_8), .B (in1[3]), .S0
       (add_21_2_n_23), .Y (out1[3]));
  MXI2XL add_21_2_g227(.A (add_21_2_n_92), .B (add_21_2_n_91), .S0
       (add_21_2_n_27), .Y (out1[7]));
  OAI21X2 add_21_2_g230(.A0 (add_21_2_n_93), .A1 (add_21_2_n_25), .B0
       (add_21_2_n_20), .Y (add_21_2_n_30));
  NOR2X1 add_21_2_g233(.A (in1[4]), .B (add_21_2_n_101), .Y
       (add_21_2_n_29));
  NOR2BX1 add_21_2_g234(.AN (in1[4]), .B (add_21_2_n_97), .Y
       (add_21_2_n_28));
  NOR2X1 add_21_2_g235(.A (add_21_2_n_18), .B (add_21_2_n_99), .Y
       (add_21_2_n_27));
  NAND2BX1 add_21_2_g236(.AN (add_21_2_n_21), .B (add_21_2_n_23), .Y
       (out1[2]));
  NOR2X4 add_21_2_g238(.A (add_21_2_n_14), .B (add_21_2_n_22), .Y
       (add_21_2_n_25));
  NAND2X1 add_21_2_g239(.A (add_21_2_n_69), .B (add_21_2_n_65), .Y
       (add_21_2_n_23));
  NOR2X6 add_21_2_g240(.A (add_21_2_n_8), .B (add_21_2_n_12), .Y
       (add_21_2_n_22));
  NOR2X1 add_21_2_g241(.A (add_21_2_n_68), .B (add_21_2_n_64), .Y
       (add_21_2_n_21));
  NOR2X2 add_21_2_g242(.A (add_21_2_n_15), .B (add_21_2_n_19), .Y
       (add_21_2_n_20));
  NOR2X2 add_21_2_g243(.A (add_21_2_n_94), .B (add_21_2_n_16), .Y
       (add_21_2_n_19));
  NAND2X1 add_21_2_g244(.A (add_21_2_n_84), .B (add_21_2_n_74), .Y
       (add_21_2_n_18));
  OR2XL add_21_2_g245(.A (add_21_2_n_10), .B (add_21_2_n_13), .Y
       (add_21_2_n_17));
  NOR2X4 add_21_2_g248(.A (in1[5]), .B (in1[4]), .Y (add_21_2_n_16));
  NOR2X2 add_21_2_g249(.A (add_21_2_n_86), .B (add_21_2_n_94), .Y
       (add_21_2_n_15));
  NOR2X4 add_21_2_g250(.A (add_21_2_n_71), .B (add_21_2_n_8), .Y
       (add_21_2_n_14));
  NAND2X1 add_21_2_g251(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_13));
  NAND2X8 add_21_2_g252(.A (in1[1]), .B (in1[0]), .Y (add_21_2_n_12));
  INVXL add_21_2_g253(.A (in1[11]), .Y (add_21_2_n_11));
  INVX1 add_21_2_g255(.A (in1[10]), .Y (add_21_2_n_10));
  CLKINVX3 add_21_2_g257(.A (in1[3]), .Y (add_21_2_n_8));
  INVXL add_21_2_g260(.A (in1[9]), .Y (add_21_2_n_6));
  INVX1 add_21_2_g261(.A (in1[8]), .Y (add_21_2_n_5));
  OR2XL add_21_2_g2(.A (add_21_2_n_28), .B (add_21_2_n_29), .Y
       (out1[4]));
  NOR2BX1 add_21_2_g263(.AN (add_21_2_n_73), .B (add_21_2_n_98), .Y
       (add_21_2_n_2));
  CLKXOR2X1 add_21_2_g264(.A (in1[5]), .B (add_21_2_n_29), .Y
       (out1[5]));
  XOR2XL add_21_2_g265(.A (in1[1]), .B (in1[0]), .Y (out1[1]));
  INVXL add_21_2_fopt(.A (add_21_2_n_66), .Y (add_21_2_n_64));
  INVXL add_21_2_fopt267(.A (add_21_2_n_66), .Y (add_21_2_n_65));
  INVXL add_21_2_fopt268(.A (add_21_2_n_12), .Y (add_21_2_n_66));
  INVXL add_21_2_fopt269(.A (add_21_2_n_70), .Y (add_21_2_n_68));
  INVXL add_21_2_fopt270(.A (add_21_2_n_70), .Y (add_21_2_n_69));
  BUFX2 add_21_2_fopt271(.A (in1[2]), .Y (add_21_2_n_70));
  CLKINVX4 add_21_2_fopt272(.A (in1[2]), .Y (add_21_2_n_71));
  INVXL add_21_2_fopt273(.A (add_21_2_n_75), .Y (add_21_2_n_73));
  INVXL add_21_2_fopt274(.A (add_21_2_n_75), .Y (add_21_2_n_74));
  INVXL add_21_2_fopt275(.A (add_21_2_n_16), .Y (add_21_2_n_75));
  INVXL add_21_2_fopt280(.A (add_21_2_n_83), .Y (add_21_2_n_82));
  INVXL add_21_2_fopt281(.A (add_21_2_n_85), .Y (add_21_2_n_83));
  INVXL add_21_2_fopt282(.A (add_21_2_n_85), .Y (add_21_2_n_84));
  BUFX2 add_21_2_fopt283(.A (in1[6]), .Y (add_21_2_n_85));
  CLKINVX3 add_21_2_fopt284(.A (in1[6]), .Y (add_21_2_n_86));
  INVXL add_21_2_fopt285(.A (add_21_2_n_90), .Y (add_21_2_n_89));
  CLKINVX2 add_21_2_fopt286(.A (add_21_2_n_30), .Y (add_21_2_n_90));
  INVXL add_21_2_fopt287(.A (add_21_2_n_92), .Y (add_21_2_n_91));
  INVXL add_21_2_fopt288(.A (add_21_2_n_93), .Y (add_21_2_n_92));
  BUFX3 add_21_2_fopt289(.A (add_21_2_n_94), .Y (add_21_2_n_93));
  CLKINVX4 add_21_2_fopt290(.A (in1[7]), .Y (add_21_2_n_94));
  INVXL add_21_2_fopt291(.A (add_21_2_n_101), .Y (add_21_2_n_97));
  INVXL add_21_2_fopt292(.A (add_21_2_n_100), .Y (add_21_2_n_98));
  INVXL add_21_2_fopt293(.A (add_21_2_n_100), .Y (add_21_2_n_99));
  INVXL add_21_2_fopt294(.A (add_21_2_n_101), .Y (add_21_2_n_100));
  CLKINVX1 add_21_2_fopt295(.A (add_21_2_n_25), .Y (add_21_2_n_101));
endmodule

