`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:41:29 CST (May  4 2021 16:41:29 UTC)

module DC_Filter_Add_12U_129_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_3, add_21_2_n_4, add_21_2_n_5, add_21_2_n_6,
       add_21_2_n_7, add_21_2_n_8, add_21_2_n_9, add_21_2_n_10;
  wire add_21_2_n_11, add_21_2_n_12, add_21_2_n_13, add_21_2_n_14,
       add_21_2_n_15, add_21_2_n_17, add_21_2_n_19, add_21_2_n_20;
  wire add_21_2_n_21, add_21_2_n_22, add_21_2_n_23, add_21_2_n_24,
       add_21_2_n_25, add_21_2_n_26, add_21_2_n_27, add_21_2_n_30;
  wire add_21_2_n_31, add_21_2_n_32, add_21_2_n_33, add_21_2_n_56,
       add_21_2_n_57, add_21_2_n_66, add_21_2_n_67, add_21_2_n_68;
  wire add_21_2_n_69, add_21_2_n_70, add_21_2_n_71, add_21_2_n_72;
  assign out1[0] = in1[0];
  INVX1 g7(.A (in1[1]), .Y (out1[1]));
  MXI2XL add_21_2_g218(.A (add_21_2_n_5), .B (in1[9]), .S0
       (add_21_2_n_32), .Y (out1[9]));
  MXI2XL add_21_2_g219(.A (add_21_2_n_6), .B (in1[11]), .S0
       (add_21_2_n_31), .Y (out1[11]));
  MXI2XL add_21_2_g220(.A (in1[5]), .B (add_21_2_n_7), .S0
       (add_21_2_n_25), .Y (out1[5]));
  MXI2XL add_21_2_g221(.A (add_21_2_n_9), .B (in1[10]), .S0
       (add_21_2_n_33), .Y (out1[10]));
  MXI2XL add_21_2_g223(.A (add_21_2_n_3), .B (in1[6]), .S0
       (add_21_2_n_30), .Y (out1[6]));
  MXI2XL add_21_2_g224(.A (add_21_2_n_4), .B (in1[8]), .S0
       (add_21_2_n_56), .Y (out1[8]));
  NOR2X1 add_21_2_g225(.A (add_21_2_n_12), .B (add_21_2_n_57), .Y
       (add_21_2_n_33));
  NOR2X1 add_21_2_g226(.A (add_21_2_n_4), .B (add_21_2_n_57), .Y
       (add_21_2_n_32));
  NOR2X1 add_21_2_g227(.A (add_21_2_n_20), .B (add_21_2_n_57), .Y
       (add_21_2_n_31));
  OAI21X1 add_21_2_g229(.A0 (add_21_2_n_7), .A1 (add_21_2_n_67), .B0
       (add_21_2_n_13), .Y (add_21_2_n_30));
  NAND2BX1 add_21_2_g230(.AN (add_21_2_n_25), .B (add_21_2_n_24), .Y
       (out1[4]));
  NAND2BX1 add_21_2_g232(.AN (add_21_2_n_19), .B (add_21_2_n_23), .Y
       (add_21_2_n_27));
  AOI21X2 add_21_2_g233(.A0 (add_21_2_n_15), .A1 (add_21_2_n_66), .B0
       (add_21_2_n_22), .Y (add_21_2_n_26));
  NOR2X1 add_21_2_g234(.A (in1[4]), .B (add_21_2_n_69), .Y
       (add_21_2_n_25));
  NAND2X1 add_21_2_g235(.A (in1[4]), .B (add_21_2_n_68), .Y
       (add_21_2_n_24));
  NAND2X2 add_21_2_g236(.A (add_21_2_n_17), .B (add_21_2_n_21), .Y
       (add_21_2_n_23));
  NOR2X1 add_21_2_g237(.A (add_21_2_n_3), .B (add_21_2_n_13), .Y
       (add_21_2_n_22));
  NOR2X2 add_21_2_g238(.A (add_21_2_n_7), .B (add_21_2_n_11), .Y
       (add_21_2_n_21));
  OR2XL add_21_2_g239(.A (add_21_2_n_9), .B (add_21_2_n_12), .Y
       (add_21_2_n_20));
  NOR2X1 add_21_2_g240(.A (add_21_2_n_11), .B (add_21_2_n_13), .Y
       (add_21_2_n_19));
  NOR2X6 add_21_2_g242(.A (add_21_2_n_8), .B (add_21_2_n_14), .Y
       (add_21_2_n_17));
  MXI2XL add_21_2_g243(.A (add_21_2_n_8), .B (in1[1]), .S0 (in1[2]), .Y
       (out1[2]));
  NOR2X1 add_21_2_g244(.A (add_21_2_n_3), .B (add_21_2_n_7), .Y
       (add_21_2_n_15));
  NAND2X8 add_21_2_g245(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_14));
  NAND2X2 add_21_2_g246(.A (in1[5]), .B (in1[4]), .Y (add_21_2_n_13));
  NAND2X1 add_21_2_g247(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_12));
  NAND2X6 add_21_2_g248(.A (in1[7]), .B (in1[6]), .Y (add_21_2_n_11));
  NAND2X1 add_21_2_g249(.A (in1[2]), .B (in1[1]), .Y (add_21_2_n_10));
  INVX1 add_21_2_g250(.A (in1[10]), .Y (add_21_2_n_9));
  CLKINVX2 add_21_2_g253(.A (in1[1]), .Y (add_21_2_n_8));
  CLKINVX2 add_21_2_g254(.A (in1[5]), .Y (add_21_2_n_7));
  INVXL add_21_2_g255(.A (in1[11]), .Y (add_21_2_n_6));
  INVXL add_21_2_g256(.A (in1[9]), .Y (add_21_2_n_5));
  INVX1 add_21_2_g257(.A (in1[8]), .Y (add_21_2_n_4));
  INVX1 add_21_2_g258(.A (in1[6]), .Y (add_21_2_n_3));
  XNOR2XL add_21_2_g2(.A (in1[7]), .B (add_21_2_n_26), .Y (out1[7]));
  XNOR2X1 add_21_2_g259(.A (in1[3]), .B (add_21_2_n_10), .Y (out1[3]));
  INVXL add_21_2_fopt(.A (add_21_2_n_57), .Y (add_21_2_n_56));
  CLKINVX2 add_21_2_fopt260(.A (add_21_2_n_27), .Y (add_21_2_n_57));
  CLKINVX1 add_21_2_fopt265(.A (add_21_2_n_72), .Y (add_21_2_n_66));
  INVXL add_21_2_fopt266(.A (add_21_2_n_71), .Y (add_21_2_n_67));
  INVXL add_21_2_fopt267(.A (add_21_2_n_70), .Y (add_21_2_n_68));
  INVXL add_21_2_fopt268(.A (add_21_2_n_70), .Y (add_21_2_n_69));
  INVXL add_21_2_fopt269(.A (add_21_2_n_71), .Y (add_21_2_n_70));
  INVXL add_21_2_fopt270(.A (add_21_2_n_72), .Y (add_21_2_n_71));
  CLKINVX1 add_21_2_fopt271(.A (add_21_2_n_17), .Y (add_21_2_n_72));
endmodule

