`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:41:26 CST (May  4 2021 16:41:26 UTC)

module DC_Filter_Add_12U_123_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_3, add_21_2_n_4, add_21_2_n_5, add_21_2_n_6,
       add_21_2_n_7, add_21_2_n_8, add_21_2_n_9, add_21_2_n_10;
  wire add_21_2_n_11, add_21_2_n_12, add_21_2_n_13, add_21_2_n_14,
       add_21_2_n_15, add_21_2_n_16, add_21_2_n_17, add_21_2_n_19;
  wire add_21_2_n_20, add_21_2_n_22, add_21_2_n_23, add_21_2_n_24,
       add_21_2_n_45, add_21_2_n_46, add_21_2_n_49, add_21_2_n_50;
  wire add_21_2_n_51;
  assign out1[0] = in1[0];
  assign out1[1] = in1[1];
  INVX1 g7(.A (in1[2]), .Y (out1[2]));
  MXI2XL add_21_2_g207(.A (add_21_2_n_5), .B (in1[9]), .S0
       (add_21_2_n_23), .Y (out1[9]));
  MXI2XL add_21_2_g209(.A (add_21_2_n_6), .B (in1[11]), .S0
       (add_21_2_n_22), .Y (out1[11]));
  MXI2XL add_21_2_g210(.A (add_21_2_n_7), .B (in1[10]), .S0
       (add_21_2_n_24), .Y (out1[10]));
  MXI2XL add_21_2_g211(.A (add_21_2_n_4), .B (in1[8]), .S0
       (add_21_2_n_45), .Y (out1[8]));
  MXI2XL add_21_2_g212(.A (add_21_2_n_9), .B (in1[7]), .S0
       (add_21_2_n_16), .Y (out1[7]));
  MXI2XL add_21_2_g213(.A (add_21_2_n_8), .B (in1[6]), .S0
       (add_21_2_n_20), .Y (out1[6]));
  NOR2X1 add_21_2_g214(.A (add_21_2_n_10), .B (add_21_2_n_46), .Y
       (add_21_2_n_24));
  NOR2X1 add_21_2_g215(.A (add_21_2_n_4), .B (add_21_2_n_46), .Y
       (add_21_2_n_23));
  NOR2X1 add_21_2_g216(.A (add_21_2_n_15), .B (add_21_2_n_46), .Y
       (add_21_2_n_22));
  MXI2XL add_21_2_g217(.A (in1[4]), .B (add_21_2_n_3), .S0
       (add_21_2_n_13), .Y (out1[4]));
  NOR2X1 add_21_2_g218(.A (add_21_2_n_50), .B (add_21_2_n_13), .Y
       (add_21_2_n_20));
  NOR2X1 add_21_2_g219(.A (add_21_2_n_3), .B (add_21_2_n_13), .Y
       (add_21_2_n_19));
  NOR3X6 add_21_2_g221(.A (add_21_2_n_13), .B (add_21_2_n_14), .C
       (add_21_2_n_12), .Y (add_21_2_n_17));
  NOR3X1 add_21_2_g222(.A (add_21_2_n_13), .B (add_21_2_n_8), .C
       (add_21_2_n_49), .Y (add_21_2_n_16));
  OR2XL add_21_2_g223(.A (add_21_2_n_7), .B (add_21_2_n_10), .Y
       (add_21_2_n_15));
  NAND2X8 add_21_2_g225(.A (in1[5]), .B (in1[4]), .Y (add_21_2_n_14));
  NOR2X6 add_21_2_g227(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_13));
  NAND2X4 add_21_2_g228(.A (in1[7]), .B (in1[6]), .Y (add_21_2_n_12));
  NAND2X1 add_21_2_g229(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_11));
  NAND2X1 add_21_2_g230(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_10));
  INVXL add_21_2_g231(.A (in1[7]), .Y (add_21_2_n_9));
  INVX1 add_21_2_g232(.A (in1[6]), .Y (add_21_2_n_8));
  INVX1 add_21_2_g233(.A (in1[10]), .Y (add_21_2_n_7));
  INVXL add_21_2_g234(.A (in1[11]), .Y (add_21_2_n_6));
  INVXL add_21_2_g235(.A (in1[9]), .Y (add_21_2_n_5));
  INVX1 add_21_2_g236(.A (in1[8]), .Y (add_21_2_n_4));
  INVX1 add_21_2_g237(.A (in1[4]), .Y (add_21_2_n_3));
  NAND2BX1 add_21_2_g2(.AN (add_21_2_n_13), .B (add_21_2_n_11), .Y
       (out1[3]));
  CLKXOR2X1 add_21_2_g239(.A (in1[5]), .B (add_21_2_n_19), .Y
       (out1[5]));
  INVXL add_21_2_fopt(.A (add_21_2_n_46), .Y (add_21_2_n_45));
  CLKINVX3 add_21_2_fopt240(.A (add_21_2_n_17), .Y (add_21_2_n_46));
  INVXL add_21_2_fopt241(.A (add_21_2_n_51), .Y (add_21_2_n_49));
  INVXL add_21_2_fopt242(.A (add_21_2_n_51), .Y (add_21_2_n_50));
  INVXL add_21_2_fopt243(.A (add_21_2_n_14), .Y (add_21_2_n_51));
endmodule

