`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  4 2021 16:44:05 CST (May  4 2021 08:44:05 UTC)

module DC_Filter_Add_8Ux4U_9U_4(in2, in1, out1);
  input [7:0] in2;
  input [3:0] in1;
  output [8:0] out1;
  wire [7:0] in2;
  wire [3:0] in1;
  wire [8:0] out1;
  wire add_23_2_n_0, add_23_2_n_2, add_23_2_n_4, add_23_2_n_6,
       add_23_2_n_8, add_23_2_n_10, add_23_2_n_12;
  ADDHX1 add_23_2_g212(.A (in2[7]), .B (add_23_2_n_12), .CO (out1[8]),
       .S (out1[7]));
  ADDHX1 add_23_2_g213(.A (in2[6]), .B (add_23_2_n_10), .CO
       (add_23_2_n_12), .S (out1[6]));
  ADDHX1 add_23_2_g214(.A (in2[5]), .B (add_23_2_n_8), .CO
       (add_23_2_n_10), .S (out1[5]));
  ADDHX1 add_23_2_g215(.A (in2[4]), .B (add_23_2_n_6), .CO
       (add_23_2_n_8), .S (out1[4]));
  ADDFX1 add_23_2_g216(.A (add_23_2_n_4), .B (in1[3]), .CI (in2[3]),
       .CO (add_23_2_n_6), .S (out1[3]));
  ADDFX1 add_23_2_g217(.A (add_23_2_n_2), .B (in1[2]), .CI (in2[2]),
       .CO (add_23_2_n_4), .S (out1[2]));
  ADDFX1 add_23_2_g218(.A (add_23_2_n_0), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_2), .S (out1[1]));
  ADDHX1 add_23_2_g219(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_0), .S
       (out1[0]));
endmodule


