`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  4 2021 16:43:34 CST (May  4 2021 08:43:34 UTC)

module DC_Filter_Add_28Sx4U_29S_4(in2, in1, out1);
  input [27:0] in2;
  input [3:0] in1;
  output [28:0] out1;
  wire [27:0] in2;
  wire [3:0] in1;
  wire [28:0] out1;
  wire add_23_2_n_0, add_23_2_n_2, add_23_2_n_4, add_23_2_n_7,
       add_23_2_n_8, add_23_2_n_10, add_23_2_n_12, add_23_2_n_14;
  wire add_23_2_n_16, add_23_2_n_17, add_23_2_n_19, add_23_2_n_22,
       add_23_2_n_24, add_23_2_n_26, add_23_2_n_28, add_23_2_n_30;
  wire add_23_2_n_32, add_23_2_n_33, add_23_2_n_35, add_23_2_n_38,
       add_23_2_n_40, add_23_2_n_42, add_23_2_n_44, add_23_2_n_46;
  wire add_23_2_n_48, add_23_2_n_50, add_23_2_n_52, add_23_2_n_55;
  INVX1 add_23_2_g726(.A (add_23_2_n_55), .Y (out1[27]));
  ADDHX1 add_23_2_g727(.A (in2[27]), .B (add_23_2_n_52), .CO
       (out1[28]), .S (add_23_2_n_55));
  XNOR2X1 add_23_2_g728(.A (in2[26]), .B (add_23_2_n_50), .Y
       (out1[26]));
  NAND2BX1 add_23_2_g729(.AN (add_23_2_n_50), .B (in2[26]), .Y
       (add_23_2_n_52));
  XNOR2X1 add_23_2_g730(.A (in2[25]), .B (add_23_2_n_48), .Y
       (out1[25]));
  NAND2BX1 add_23_2_g731(.AN (add_23_2_n_48), .B (in2[25]), .Y
       (add_23_2_n_50));
  XNOR2X1 add_23_2_g732(.A (in2[24]), .B (add_23_2_n_46), .Y
       (out1[24]));
  NAND2BX1 add_23_2_g733(.AN (add_23_2_n_46), .B (in2[24]), .Y
       (add_23_2_n_48));
  XNOR2X1 add_23_2_g734(.A (in2[23]), .B (add_23_2_n_44), .Y
       (out1[23]));
  NAND2BX1 add_23_2_g735(.AN (add_23_2_n_44), .B (in2[23]), .Y
       (add_23_2_n_46));
  XNOR2X1 add_23_2_g736(.A (in2[22]), .B (add_23_2_n_42), .Y
       (out1[22]));
  NAND2BX1 add_23_2_g737(.AN (add_23_2_n_42), .B (in2[22]), .Y
       (add_23_2_n_44));
  XNOR2X1 add_23_2_g738(.A (in2[21]), .B (add_23_2_n_40), .Y
       (out1[21]));
  NAND2BX1 add_23_2_g739(.AN (add_23_2_n_40), .B (in2[21]), .Y
       (add_23_2_n_42));
  XNOR2X1 add_23_2_g740(.A (in2[20]), .B (add_23_2_n_38), .Y
       (out1[20]));
  NAND2BX1 add_23_2_g741(.AN (add_23_2_n_38), .B (in2[20]), .Y
       (add_23_2_n_40));
  XNOR2X1 add_23_2_g742(.A (in2[19]), .B (add_23_2_n_35), .Y
       (out1[19]));
  NAND2BX1 add_23_2_g743(.AN (add_23_2_n_35), .B (in2[19]), .Y
       (add_23_2_n_38));
  XNOR2X1 add_23_2_g744(.A (in2[17]), .B (add_23_2_n_33), .Y
       (out1[17]));
  XNOR2X1 add_23_2_g745(.A (in2[18]), .B (add_23_2_n_32), .Y
       (out1[18]));
  NAND2BX1 add_23_2_g746(.AN (add_23_2_n_32), .B (in2[18]), .Y
       (add_23_2_n_35));
  XNOR2X1 add_23_2_g747(.A (in2[16]), .B (add_23_2_n_30), .Y
       (out1[16]));
  NAND2BX1 add_23_2_g748(.AN (add_23_2_n_30), .B (in2[16]), .Y
       (add_23_2_n_33));
  NAND3BXL add_23_2_g749(.AN (add_23_2_n_30), .B (in2[17]), .C
       (in2[16]), .Y (add_23_2_n_32));
  XNOR2X1 add_23_2_g750(.A (in2[15]), .B (add_23_2_n_28), .Y
       (out1[15]));
  NAND2BX1 add_23_2_g751(.AN (add_23_2_n_28), .B (in2[15]), .Y
       (add_23_2_n_30));
  XNOR2X1 add_23_2_g752(.A (in2[14]), .B (add_23_2_n_26), .Y
       (out1[14]));
  NAND2BX1 add_23_2_g753(.AN (add_23_2_n_26), .B (in2[14]), .Y
       (add_23_2_n_28));
  XNOR2X1 add_23_2_g754(.A (in2[13]), .B (add_23_2_n_24), .Y
       (out1[13]));
  NAND2BX1 add_23_2_g755(.AN (add_23_2_n_24), .B (in2[13]), .Y
       (add_23_2_n_26));
  XNOR2X1 add_23_2_g756(.A (in2[12]), .B (add_23_2_n_22), .Y
       (out1[12]));
  NAND2BX1 add_23_2_g757(.AN (add_23_2_n_22), .B (in2[12]), .Y
       (add_23_2_n_24));
  XNOR2X1 add_23_2_g758(.A (in2[11]), .B (add_23_2_n_19), .Y
       (out1[11]));
  NAND2BX1 add_23_2_g759(.AN (add_23_2_n_19), .B (in2[11]), .Y
       (add_23_2_n_22));
  XNOR2X1 add_23_2_g760(.A (in2[9]), .B (add_23_2_n_17), .Y (out1[9]));
  XNOR2X1 add_23_2_g761(.A (in2[10]), .B (add_23_2_n_16), .Y
       (out1[10]));
  NAND2BX1 add_23_2_g762(.AN (add_23_2_n_16), .B (in2[10]), .Y
       (add_23_2_n_19));
  XNOR2X1 add_23_2_g763(.A (in2[8]), .B (add_23_2_n_14), .Y (out1[8]));
  NAND2BX1 add_23_2_g764(.AN (add_23_2_n_14), .B (in2[8]), .Y
       (add_23_2_n_17));
  NAND3BXL add_23_2_g765(.AN (add_23_2_n_14), .B (in2[9]), .C (in2[8]),
       .Y (add_23_2_n_16));
  XNOR2X1 add_23_2_g766(.A (in2[7]), .B (add_23_2_n_12), .Y (out1[7]));
  NAND2BX1 add_23_2_g767(.AN (add_23_2_n_12), .B (in2[7]), .Y
       (add_23_2_n_14));
  XNOR2X1 add_23_2_g768(.A (in2[6]), .B (add_23_2_n_10), .Y (out1[6]));
  NAND2BX1 add_23_2_g769(.AN (add_23_2_n_10), .B (in2[6]), .Y
       (add_23_2_n_12));
  XNOR2X1 add_23_2_g770(.A (in2[5]), .B (add_23_2_n_8), .Y (out1[5]));
  NAND2BX1 add_23_2_g771(.AN (add_23_2_n_8), .B (in2[5]), .Y
       (add_23_2_n_10));
  XOR2XL add_23_2_g772(.A (in2[4]), .B (add_23_2_n_7), .Y (out1[4]));
  NAND2X1 add_23_2_g773(.A (in2[4]), .B (add_23_2_n_7), .Y
       (add_23_2_n_8));
  ADDFX1 add_23_2_g774(.A (add_23_2_n_4), .B (in1[3]), .CI (in2[3]),
       .CO (add_23_2_n_7), .S (out1[3]));
  ADDFX1 add_23_2_g775(.A (add_23_2_n_2), .B (in1[2]), .CI (in2[2]),
       .CO (add_23_2_n_4), .S (out1[2]));
  ADDFX1 add_23_2_g776(.A (add_23_2_n_0), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_2), .S (out1[1]));
  ADDHX1 add_23_2_g777(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_0), .S
       (out1[0]));
endmodule


