`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 02:01:32 CST (May  4 2021 18:01:32 UTC)

module DC_Filter_Add_12U_55_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_2, add_21_2_n_4, add_21_2_n_5, add_21_2_n_6,
       add_21_2_n_7, add_21_2_n_8, add_21_2_n_9, add_21_2_n_10;
  wire add_21_2_n_11, add_21_2_n_13, add_21_2_n_14, add_21_2_n_15,
       add_21_2_n_16, add_21_2_n_17, add_21_2_n_18, add_21_2_n_19;
  wire add_21_2_n_21, add_21_2_n_22;
  assign out1[0] = in1[0];
  assign out1[1] = in1[1];
  assign out1[2] = in1[2];
  INVX1 g7(.A (in1[3]), .Y (out1[3]));
  MXI2XL add_21_2_g192(.A (in1[6]), .B (add_21_2_n_5), .S0
       (add_21_2_n_2), .Y (out1[6]));
  MXI2X1 add_21_2_g194(.A (add_21_2_n_7), .B (in1[10]), .S0
       (add_21_2_n_22), .Y (out1[10]));
  MXI2XL add_21_2_g195(.A (in1[8]), .B (add_21_2_n_8), .S0
       (add_21_2_n_15), .Y (out1[8]));
  MXI2XL add_21_2_g196(.A (in1[7]), .B (add_21_2_n_4), .S0
       (add_21_2_n_17), .Y (out1[7]));
  NOR2X1 add_21_2_g197(.A (add_21_2_n_10), .B (add_21_2_n_15), .Y
       (add_21_2_n_22));
  NAND2X1 add_21_2_g198(.A (in1[8]), .B (add_21_2_n_16), .Y
       (add_21_2_n_21));
  NAND2BX1 add_21_2_g199(.AN (add_21_2_n_18), .B (add_21_2_n_2), .Y
       (out1[5]));
  NAND2X1 add_21_2_g200(.A (add_21_2_n_14), .B (add_21_2_n_16), .Y
       (add_21_2_n_19));
  NOR2BX1 add_21_2_g201(.AN (in1[5]), .B (add_21_2_n_9), .Y
       (add_21_2_n_18));
  NAND2X1 add_21_2_g203(.A (add_21_2_n_9), .B (add_21_2_n_11), .Y
       (add_21_2_n_17));
  CLKINVX2 add_21_2_g204(.A (add_21_2_n_16), .Y (add_21_2_n_15));
  NAND2X4 add_21_2_g205(.A (add_21_2_n_9), .B (add_21_2_n_13), .Y
       (add_21_2_n_16));
  NOR2X1 add_21_2_g206(.A (add_21_2_n_7), .B (add_21_2_n_10), .Y
       (add_21_2_n_14));
  NOR3X8 add_21_2_g207(.A (in1[5]), .B (in1[7]), .C (in1[6]), .Y
       (add_21_2_n_13));
  MXI2XL add_21_2_g208(.A (add_21_2_n_6), .B (in1[4]), .S0 (in1[3]), .Y
       (out1[4]));
  NOR2X1 add_21_2_g209(.A (in1[6]), .B (in1[5]), .Y (add_21_2_n_11));
  NAND2X4 add_21_2_g210(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_10));
  NAND2X6 add_21_2_g211(.A (in1[4]), .B (in1[3]), .Y (add_21_2_n_9));
  INVX1 add_21_2_g213(.A (in1[8]), .Y (add_21_2_n_8));
  INVX1 add_21_2_g214(.A (in1[10]), .Y (add_21_2_n_7));
  INVX1 add_21_2_g217(.A (in1[4]), .Y (add_21_2_n_6));
  INVXL add_21_2_g218(.A (in1[6]), .Y (add_21_2_n_5));
  INVX1 add_21_2_g219(.A (in1[7]), .Y (add_21_2_n_4));
  NAND2BX1 add_21_2_g2(.AN (in1[5]), .B (add_21_2_n_9), .Y
       (add_21_2_n_2));
  XNOR2X1 add_21_2_g220(.A (in1[9]), .B (add_21_2_n_21), .Y (out1[9]));
  XNOR2XL add_21_2_g221(.A (in1[11]), .B (add_21_2_n_19), .Y
       (out1[11]));
endmodule


