`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 02:00:57 CST (May  4 2021 18:00:57 UTC)

module DC_Filter_Add_12U_1_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_3, add_21_2_n_4, add_21_2_n_5, add_21_2_n_6,
       add_21_2_n_7, add_21_2_n_8, add_21_2_n_9, add_21_2_n_10;
  wire add_21_2_n_11, add_21_2_n_12, add_21_2_n_13, add_21_2_n_14,
       add_21_2_n_16, add_21_2_n_17, add_21_2_n_18, add_21_2_n_19;
  wire add_21_2_n_20, add_21_2_n_22, add_21_2_n_23, add_21_2_n_24,
       add_21_2_n_25, add_21_2_n_26, add_21_2_n_30, add_21_2_n_31;
  wire add_21_2_n_32, add_21_2_n_57, add_21_2_n_58, add_21_2_n_60;
  INVX1 g7(.A (in1[0]), .Y (out1[0]));
  MXI2X1 add_21_2_g211(.A (add_21_2_n_6), .B (in1[9]), .S0
       (add_21_2_n_31), .Y (out1[9]));
  MXI2X1 add_21_2_g212(.A (add_21_2_n_10), .B (in1[11]), .S0
       (add_21_2_n_30), .Y (out1[11]));
  MXI2X1 add_21_2_g214(.A (add_21_2_n_9), .B (in1[10]), .S0
       (add_21_2_n_32), .Y (out1[10]));
  MXI2X1 add_21_2_g215(.A (add_21_2_n_4), .B (in1[8]), .S0
       (add_21_2_n_57), .Y (out1[8]));
  NOR2X1 add_21_2_g218(.A (add_21_2_n_11), .B (add_21_2_n_58), .Y
       (add_21_2_n_32));
  NOR2X1 add_21_2_g219(.A (add_21_2_n_4), .B (add_21_2_n_58), .Y
       (add_21_2_n_31));
  NOR2X1 add_21_2_g220(.A (add_21_2_n_17), .B (add_21_2_n_58), .Y
       (add_21_2_n_30));
  MXI2XL add_21_2_g221(.A (in1[6]), .B (add_21_2_n_8), .S0
       (add_21_2_n_24), .Y (out1[6]));
  NAND2BX1 add_21_2_g223(.AN (add_21_2_n_23), .B (add_21_2_n_22), .Y
       (out1[4]));
  NAND2X2 add_21_2_g225(.A (add_21_2_n_18), .B (add_21_2_n_25), .Y
       (add_21_2_n_26));
  NAND2X4 add_21_2_g226(.A (in1[6]), .B (add_21_2_n_19), .Y
       (add_21_2_n_25));
  NOR2BX1 add_21_2_g227(.AN (add_21_2_n_13), .B (add_21_2_n_60), .Y
       (add_21_2_n_24));
  NOR2X2 add_21_2_g228(.A (in1[4]), .B (add_21_2_n_60), .Y
       (add_21_2_n_23));
  NAND2X1 add_21_2_g229(.A (in1[4]), .B (add_21_2_n_60), .Y
       (add_21_2_n_22));
  MXI2XL add_21_2_g230(.A (in1[2]), .B (add_21_2_n_5), .S0
       (add_21_2_n_12), .Y (out1[2]));
  NOR2X1 add_21_2_g231(.A (add_21_2_n_5), .B (add_21_2_n_12), .Y
       (add_21_2_n_20));
  NOR2X6 add_21_2_g232(.A (add_21_2_n_12), .B (add_21_2_n_14), .Y
       (add_21_2_n_19));
  NOR2X2 add_21_2_g233(.A (in1[7]), .B (add_21_2_n_16), .Y
       (add_21_2_n_18));
  OR2XL add_21_2_g234(.A (add_21_2_n_9), .B (add_21_2_n_11), .Y
       (add_21_2_n_17));
  NOR2X2 add_21_2_g236(.A (add_21_2_n_8), .B (add_21_2_n_13), .Y
       (add_21_2_n_16));
  MXI2XL add_21_2_g237(.A (in1[1]), .B (add_21_2_n_7), .S0 (in1[0]), .Y
       (out1[1]));
  NAND2X8 add_21_2_g238(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_14));
  NOR2X6 add_21_2_g239(.A (in1[5]), .B (in1[4]), .Y (add_21_2_n_13));
  NOR2X6 add_21_2_g240(.A (in1[1]), .B (in1[0]), .Y (add_21_2_n_12));
  NAND2X1 add_21_2_g241(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_11));
  INVXL add_21_2_g242(.A (in1[11]), .Y (add_21_2_n_10));
  INVX1 add_21_2_g243(.A (in1[10]), .Y (add_21_2_n_9));
  INVX1 add_21_2_g246(.A (in1[6]), .Y (add_21_2_n_8));
  INVX1 add_21_2_g247(.A (in1[1]), .Y (add_21_2_n_7));
  INVXL add_21_2_g248(.A (in1[9]), .Y (add_21_2_n_6));
  INVX1 add_21_2_g250(.A (in1[2]), .Y (add_21_2_n_5));
  INVX1 add_21_2_g251(.A (in1[8]), .Y (add_21_2_n_4));
  NAND2BX1 add_21_2_g2(.AN (add_21_2_n_16), .B (add_21_2_n_25), .Y
       (add_21_2_n_3));
  CLKXOR2X1 add_21_2_g252(.A (in1[5]), .B (add_21_2_n_23), .Y
       (out1[5]));
  CLKXOR2X1 add_21_2_g253(.A (in1[3]), .B (add_21_2_n_20), .Y
       (out1[3]));
  XNOR2X1 add_21_2_g254(.A (in1[7]), .B (add_21_2_n_3), .Y (out1[7]));
  INVXL add_21_2_fopt(.A (add_21_2_n_58), .Y (add_21_2_n_57));
  CLKINVX3 add_21_2_fopt255(.A (add_21_2_n_26), .Y (add_21_2_n_58));
  BUFX3 add_21_2_fopt256(.A (add_21_2_n_19), .Y (add_21_2_n_60));
endmodule


