`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  4 2021 16:15:48 CST (May  4 2021 08:15:48 UTC)

module DC_Filter_Add_12Ux2U_12U_4(in2, in1, out1);
  input [11:0] in2;
  input [1:0] in1;
  output [11:0] out1;
  wire [11:0] in2;
  wire [1:0] in1;
  wire [11:0] out1;
  wire add_23_2_n_0, add_23_2_n_3, add_23_2_n_4, add_23_2_n_6,
       add_23_2_n_8, add_23_2_n_10, add_23_2_n_12, add_23_2_n_14;
  wire add_23_2_n_16, add_23_2_n_18, add_23_2_n_20;
  XNOR2X1 add_23_2_g281(.A (in2[11]), .B (add_23_2_n_20), .Y
       (out1[11]));
  XNOR2X1 add_23_2_g282(.A (in2[10]), .B (add_23_2_n_18), .Y
       (out1[10]));
  NAND2BX1 add_23_2_g283(.AN (add_23_2_n_18), .B (in2[10]), .Y
       (add_23_2_n_20));
  XNOR2X1 add_23_2_g284(.A (in2[9]), .B (add_23_2_n_16), .Y (out1[9]));
  NAND2BX1 add_23_2_g285(.AN (add_23_2_n_16), .B (in2[9]), .Y
       (add_23_2_n_18));
  XNOR2X1 add_23_2_g286(.A (in2[8]), .B (add_23_2_n_14), .Y (out1[8]));
  NAND2BX1 add_23_2_g287(.AN (add_23_2_n_14), .B (in2[8]), .Y
       (add_23_2_n_16));
  XNOR2X1 add_23_2_g288(.A (in2[7]), .B (add_23_2_n_12), .Y (out1[7]));
  NAND2BX1 add_23_2_g289(.AN (add_23_2_n_12), .B (in2[7]), .Y
       (add_23_2_n_14));
  XNOR2X1 add_23_2_g290(.A (in2[6]), .B (add_23_2_n_10), .Y (out1[6]));
  NAND2BX1 add_23_2_g291(.AN (add_23_2_n_10), .B (in2[6]), .Y
       (add_23_2_n_12));
  XNOR2X1 add_23_2_g292(.A (in2[5]), .B (add_23_2_n_8), .Y (out1[5]));
  NAND2BX1 add_23_2_g293(.AN (add_23_2_n_8), .B (in2[5]), .Y
       (add_23_2_n_10));
  XNOR2X1 add_23_2_g294(.A (in2[4]), .B (add_23_2_n_6), .Y (out1[4]));
  NAND2BX1 add_23_2_g295(.AN (add_23_2_n_6), .B (in2[4]), .Y
       (add_23_2_n_8));
  XNOR2X1 add_23_2_g296(.A (in2[3]), .B (add_23_2_n_4), .Y (out1[3]));
  NAND2BX1 add_23_2_g297(.AN (add_23_2_n_4), .B (in2[3]), .Y
       (add_23_2_n_6));
  XOR2XL add_23_2_g298(.A (in2[2]), .B (add_23_2_n_3), .Y (out1[2]));
  NAND2X1 add_23_2_g299(.A (in2[2]), .B (add_23_2_n_3), .Y
       (add_23_2_n_4));
  ADDFX1 add_23_2_g300(.A (add_23_2_n_0), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_3), .S (out1[1]));
  ADDHX1 add_23_2_g301(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_0), .S
       (out1[0]));
endmodule

