`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:23:02 CST (May  4 2021 16:23:02 UTC)

module DC_Filter_Add_12Ux3U_12U_4(in2, in1, out1);
  input [11:0] in2;
  input [2:0] in1;
  output [11:0] out1;
  wire [11:0] in2;
  wire [2:0] in1;
  wire [11:0] out1;
  wire add_23_2_n_0, add_23_2_n_2, add_23_2_n_5, add_23_2_n_6,
       add_23_2_n_8, add_23_2_n_10, add_23_2_n_12, add_23_2_n_14;
  wire add_23_2_n_16, add_23_2_n_18, add_23_2_n_20;
  XNOR2X1 add_23_2_g296(.A (in2[11]), .B (add_23_2_n_20), .Y
       (out1[11]));
  XNOR2X1 add_23_2_g297(.A (in2[10]), .B (add_23_2_n_18), .Y
       (out1[10]));
  NAND2BX1 add_23_2_g298(.AN (add_23_2_n_18), .B (in2[10]), .Y
       (add_23_2_n_20));
  XNOR2X1 add_23_2_g299(.A (in2[9]), .B (add_23_2_n_16), .Y (out1[9]));
  NAND2BX1 add_23_2_g300(.AN (add_23_2_n_16), .B (in2[9]), .Y
       (add_23_2_n_18));
  XNOR2X1 add_23_2_g301(.A (in2[8]), .B (add_23_2_n_14), .Y (out1[8]));
  NAND2BX1 add_23_2_g302(.AN (add_23_2_n_14), .B (in2[8]), .Y
       (add_23_2_n_16));
  XNOR2X1 add_23_2_g303(.A (in2[7]), .B (add_23_2_n_12), .Y (out1[7]));
  NAND2BX1 add_23_2_g304(.AN (add_23_2_n_12), .B (in2[7]), .Y
       (add_23_2_n_14));
  XNOR2X1 add_23_2_g305(.A (in2[6]), .B (add_23_2_n_10), .Y (out1[6]));
  NAND2BX1 add_23_2_g306(.AN (add_23_2_n_10), .B (in2[6]), .Y
       (add_23_2_n_12));
  XNOR2X1 add_23_2_g307(.A (in2[5]), .B (add_23_2_n_8), .Y (out1[5]));
  NAND2BX1 add_23_2_g308(.AN (add_23_2_n_8), .B (in2[5]), .Y
       (add_23_2_n_10));
  XNOR2X1 add_23_2_g309(.A (in2[4]), .B (add_23_2_n_6), .Y (out1[4]));
  NAND2BX1 add_23_2_g310(.AN (add_23_2_n_6), .B (in2[4]), .Y
       (add_23_2_n_8));
  XOR2XL add_23_2_g311(.A (in2[3]), .B (add_23_2_n_5), .Y (out1[3]));
  NAND2X1 add_23_2_g312(.A (in2[3]), .B (add_23_2_n_5), .Y
       (add_23_2_n_6));
  ADDFX1 add_23_2_g313(.A (add_23_2_n_2), .B (in1[2]), .CI (in2[2]),
       .CO (add_23_2_n_5), .S (out1[2]));
  ADDFX1 add_23_2_g314(.A (add_23_2_n_0), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_2), .S (out1[1]));
  ADDHX1 add_23_2_g315(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_0), .S
       (out1[0]));
endmodule


