`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:42:24 CST (May  4 2021 16:42:24 UTC)

module DC_Filter_Add_12U_212_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_0, add_21_2_n_5, add_21_2_n_6, add_21_2_n_7,
       add_21_2_n_8, add_21_2_n_9, add_21_2_n_10, add_21_2_n_11;
  wire add_21_2_n_12, add_21_2_n_13, add_21_2_n_14, add_21_2_n_15,
       add_21_2_n_18, add_21_2_n_19, add_21_2_n_20, add_21_2_n_21;
  wire add_21_2_n_23, add_21_2_n_25, add_21_2_n_26, add_21_2_n_27,
       add_21_2_n_29, add_21_2_n_30, add_21_2_n_54, add_21_2_n_55;
  wire add_21_2_n_56, add_21_2_n_57, add_21_2_n_59, add_21_2_n_60,
       add_21_2_n_61, add_21_2_n_62, add_21_2_n_63;
  assign out1[0] = in1[0];
  INVX1 g7(.A (in1[1]), .Y (out1[1]));
  MXI2XL add_21_2_g209(.A (add_21_2_n_8), .B (in1[9]), .S0
       (add_21_2_n_27), .Y (out1[9]));
  MXI2XL add_21_2_g210(.A (add_21_2_n_59), .B (add_21_2_n_60), .S0
       (add_21_2_n_29), .Y (out1[7]));
  NAND2BX1 add_21_2_g211(.AN (add_21_2_n_0), .B (add_21_2_n_30), .Y
       (out1[5]));
  MXI2XL add_21_2_g212(.A (add_21_2_n_10), .B (in1[11]), .S0
       (add_21_2_n_25), .Y (out1[11]));
  MXI2XL add_21_2_g213(.A (add_21_2_n_9), .B (in1[10]), .S0
       (add_21_2_n_26), .Y (out1[10]));
  NAND2BX1 add_21_2_g214(.AN (in1[5]), .B (add_21_2_n_21), .Y
       (add_21_2_n_30));
  NAND2XL add_21_2_g216(.A (add_21_2_n_15), .B (add_21_2_n_21), .Y
       (add_21_2_n_29));
  MXI2XL add_21_2_g217(.A (add_21_2_n_7), .B (in1[8]), .S0
       (add_21_2_n_55), .Y (out1[8]));
  NOR2X1 add_21_2_g218(.A (add_21_2_n_7), .B (add_21_2_n_56), .Y
       (add_21_2_n_27));
  NOR2X1 add_21_2_g219(.A (add_21_2_n_12), .B (add_21_2_n_56), .Y
       (add_21_2_n_26));
  NOR2X1 add_21_2_g220(.A (add_21_2_n_19), .B (add_21_2_n_56), .Y
       (add_21_2_n_25));
  NAND2X1 add_21_2_g223(.A (add_21_2_n_54), .B (add_21_2_n_20), .Y
       (add_21_2_n_23));
  MXI2XL add_21_2_g224(.A (add_21_2_n_6), .B (in1[4]), .S0
       (add_21_2_n_57), .Y (out1[4]));
  NAND2X1 add_21_2_g225(.A (in1[4]), .B (add_21_2_n_18), .Y
       (add_21_2_n_21));
  NAND2X2 add_21_2_g226(.A (add_21_2_n_14), .B (add_21_2_n_18), .Y
       (add_21_2_n_20));
  OR2XL add_21_2_g227(.A (add_21_2_n_9), .B (add_21_2_n_12), .Y
       (add_21_2_n_19));
  NOR2X6 add_21_2_g228(.A (add_21_2_n_5), .B (add_21_2_n_13), .Y
       (add_21_2_n_18));
  MXI2XL add_21_2_g230(.A (add_21_2_n_5), .B (in1[1]), .S0 (in1[2]), .Y
       (out1[2]));
  NOR2X1 add_21_2_g231(.A (in1[6]), .B (in1[5]), .Y (add_21_2_n_15));
  NOR2X2 add_21_2_g232(.A (add_21_2_n_63), .B (add_21_2_n_6), .Y
       (add_21_2_n_14));
  NAND2X8 add_21_2_g233(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_13));
  NAND2X1 add_21_2_g234(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_12));
  NAND2X1 add_21_2_g235(.A (in1[2]), .B (in1[1]), .Y (add_21_2_n_11));
  INVXL add_21_2_g236(.A (in1[11]), .Y (add_21_2_n_10));
  INVX1 add_21_2_g237(.A (in1[10]), .Y (add_21_2_n_9));
  INVXL add_21_2_g238(.A (in1[9]), .Y (add_21_2_n_8));
  INVX1 add_21_2_g239(.A (in1[8]), .Y (add_21_2_n_7));
  INVX1 add_21_2_g240(.A (in1[4]), .Y (add_21_2_n_6));
  CLKINVX2 add_21_2_g242(.A (in1[1]), .Y (add_21_2_n_5));
  XNOR2X1 add_21_2_g2(.A (in1[3]), .B (add_21_2_n_11), .Y (out1[3]));
  XNOR2X1 add_21_2_g246(.A (in1[6]), .B (add_21_2_n_30), .Y (out1[6]));
  NOR2BXL add_21_2_g247(.AN (in1[5]), .B (add_21_2_n_21), .Y
       (add_21_2_n_0));
  OAI21X1 add_21_2_g248(.A0 (in1[5]), .A1 (in1[6]), .B0
       (add_21_2_n_61), .Y (add_21_2_n_54));
  INVXL add_21_2_fopt(.A (add_21_2_n_56), .Y (add_21_2_n_55));
  CLKINVX2 add_21_2_fopt249(.A (add_21_2_n_23), .Y (add_21_2_n_56));
  BUFX2 add_21_2_fopt250(.A (add_21_2_n_18), .Y (add_21_2_n_57));
  INVXL add_21_2_fopt251(.A (add_21_2_n_60), .Y (add_21_2_n_59));
  INVXL add_21_2_fopt252(.A (add_21_2_n_62), .Y (add_21_2_n_60));
  INVXL add_21_2_fopt253(.A (add_21_2_n_62), .Y (add_21_2_n_61));
  CLKINVX1 add_21_2_fopt254(.A (in1[7]), .Y (add_21_2_n_62));
  CLKINVX2 add_21_2_fopt255(.A (in1[7]), .Y (add_21_2_n_63));
endmodule


