`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:46:58 CST (May  4 2021 16:46:58 UTC)

module DC_Filter_Add2i256Mul2i258Add2u1Mul2i3u2_1(in2, in1, out1);
  input [1:0] in2;
  input in1;
  output [11:0] out1;
  wire [1:0] in2;
  wire in1;
  wire [11:0] out1;
  wire csa_tree_add_26_2_groupi_n_0, csa_tree_add_26_2_groupi_n_2,
       csa_tree_add_32_2_groupi_n_1, csa_tree_add_32_2_groupi_n_2,
       csa_tree_add_32_2_groupi_n_4;
  assign out1[0] = 1'b0;
  assign out1[5] = 1'b0;
  assign out1[6] = 1'b0;
  assign out1[7] = 1'b0;
  INVX1 g8(.A (out1[1]), .Y (out1[8]));
  MXI2X1 csa_tree_add_32_2_groupi_g164(.A
       (csa_tree_add_32_2_groupi_n_1), .B (out1[4]), .S0
       (csa_tree_add_32_2_groupi_n_4), .Y (out1[11]));
  ADDHX1 csa_tree_add_32_2_groupi_g165(.A (out1[3]), .B
       (csa_tree_add_32_2_groupi_n_2), .CO
       (csa_tree_add_32_2_groupi_n_4), .S (out1[10]));
  ADDHXL csa_tree_add_32_2_groupi_g166(.A (out1[2]), .B (out1[1]), .CO
       (csa_tree_add_32_2_groupi_n_2), .S (out1[9]));
  INVX1 csa_tree_add_32_2_groupi_g167(.A (out1[4]), .Y
       (csa_tree_add_32_2_groupi_n_1));
  ADDHX1 csa_tree_add_26_2_groupi_g81(.A (in2[1]), .B
       (csa_tree_add_26_2_groupi_n_2), .CO (out1[4]), .S (out1[3]));
  ADDFX1 csa_tree_add_26_2_groupi_g82(.A (in2[1]), .B (in2[0]), .CI
       (csa_tree_add_26_2_groupi_n_0), .CO
       (csa_tree_add_26_2_groupi_n_2), .S (out1[2]));
  ADDHX1 csa_tree_add_26_2_groupi_g83(.A (in2[0]), .B (in1), .CO
       (csa_tree_add_26_2_groupi_n_0), .S (out1[1]));
endmodule


