`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:41:17 CST (May  4 2021 16:41:17 UTC)

module DC_Filter_Add_12U_74_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_2, add_21_2_n_5, add_21_2_n_6, add_21_2_n_7,
       add_21_2_n_8, add_21_2_n_9, add_21_2_n_11, add_21_2_n_12;
  wire add_21_2_n_13, add_21_2_n_14, add_21_2_n_17, add_21_2_n_18,
       add_21_2_n_19, add_21_2_n_20, add_21_2_n_22, add_21_2_n_25;
  wire add_21_2_n_26, add_21_2_n_27, add_21_2_n_28, add_21_2_n_29,
       add_21_2_n_30, add_21_2_n_31, add_21_2_n_32, add_21_2_n_57;
  wire add_21_2_n_58, add_21_2_n_59, add_21_2_n_64, add_21_2_n_65,
       add_21_2_n_66, add_21_2_n_67, add_21_2_n_69, add_21_2_n_70;
  wire add_21_2_n_71, add_21_2_n_76;
  INVX1 g7(.A (in1[0]), .Y (out1[0]));
  MXI2XL add_21_2_g213(.A (add_21_2_n_9), .B (in1[5]), .S0
       (add_21_2_n_28), .Y (out1[5]));
  MXI2XL add_21_2_g215(.A (in1[10]), .B (add_21_2_n_7), .S0
       (add_21_2_n_31), .Y (out1[10]));
  MXI2XL add_21_2_g217(.A (add_21_2_n_5), .B (in1[6]), .S0
       (add_21_2_n_29), .Y (out1[6]));
  MXI2XL add_21_2_g218(.A (add_21_2_n_8), .B (in1[7]), .S0
       (add_21_2_n_25), .Y (out1[7]));
  NAND2XL add_21_2_g219(.A (in1[8]), .B (add_21_2_n_26), .Y
       (add_21_2_n_32));
  NAND2BXL add_21_2_g220(.AN (add_21_2_n_11), .B (add_21_2_n_26), .Y
       (add_21_2_n_31));
  NAND2XL add_21_2_g222(.A (add_21_2_n_19), .B (add_21_2_n_26), .Y
       (add_21_2_n_30));
  NOR2X1 add_21_2_g223(.A (add_21_2_n_64), .B (add_21_2_n_57), .Y
       (add_21_2_n_29));
  NOR2X1 add_21_2_g225(.A (in1[4]), .B (add_21_2_n_57), .Y
       (add_21_2_n_28));
  NOR2BX1 add_21_2_g226(.AN (in1[4]), .B (add_21_2_n_59), .Y
       (add_21_2_n_27));
  NAND2X2 add_21_2_g228(.A (add_21_2_n_22), .B (add_21_2_n_17), .Y
       (add_21_2_n_26));
  NOR2X1 add_21_2_g229(.A (add_21_2_n_18), .B (add_21_2_n_57), .Y
       (add_21_2_n_25));
  NAND2BX1 add_21_2_g231(.AN (add_21_2_n_2), .B (add_21_2_n_58), .Y
       (out1[3]));
  NOR2X4 add_21_2_g233(.A (in1[3]), .B (add_21_2_n_20), .Y
       (add_21_2_n_22));
  MXI2XL add_21_2_g236(.A (add_21_2_n_69), .B (add_21_2_n_70), .S0
       (add_21_2_n_76), .Y (out1[2]));
  NOR2X6 add_21_2_g237(.A (add_21_2_n_71), .B (add_21_2_n_12), .Y
       (add_21_2_n_20));
  NOR2X1 add_21_2_g238(.A (add_21_2_n_7), .B (add_21_2_n_11), .Y
       (add_21_2_n_19));
  NAND2X1 add_21_2_g239(.A (add_21_2_n_5), .B (add_21_2_n_65), .Y
       (add_21_2_n_18));
  NOR2X2 add_21_2_g240(.A (add_21_2_n_67), .B (add_21_2_n_13), .Y
       (add_21_2_n_17));
  MXI2XL add_21_2_g241(.A (in1[1]), .B (add_21_2_n_6), .S0 (in1[0]), .Y
       (out1[1]));
  NOR2X6 add_21_2_g243(.A (in1[5]), .B (in1[4]), .Y (add_21_2_n_14));
  NAND2X2 add_21_2_g244(.A (add_21_2_n_8), .B (add_21_2_n_5), .Y
       (add_21_2_n_13));
  NOR2X8 add_21_2_g245(.A (in1[1]), .B (in1[0]), .Y (add_21_2_n_12));
  NAND2X1 add_21_2_g246(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_11));
  INVX1 add_21_2_g248(.A (in1[5]), .Y (add_21_2_n_9));
  CLKINVX4 add_21_2_g249(.A (in1[7]), .Y (add_21_2_n_8));
  INVX1 add_21_2_g250(.A (in1[10]), .Y (add_21_2_n_7));
  INVX1 add_21_2_g253(.A (in1[1]), .Y (add_21_2_n_6));
  CLKINVX3 add_21_2_g254(.A (in1[6]), .Y (add_21_2_n_5));
  OR2XL add_21_2_g2(.A (add_21_2_n_27), .B (add_21_2_n_28), .Y
       (out1[4]));
  CLKXOR2X1 add_21_2_g256(.A (in1[8]), .B (add_21_2_n_26), .Y
       (out1[8]));
  AND2XL add_21_2_g257(.A (in1[3]), .B (add_21_2_n_20), .Y
       (add_21_2_n_2));
  XNOR2XL add_21_2_g258(.A (in1[11]), .B (add_21_2_n_30), .Y
       (out1[11]));
  XNOR2XL add_21_2_g259(.A (in1[9]), .B (add_21_2_n_32), .Y (out1[9]));
  INVXL add_21_2_fopt(.A (add_21_2_n_59), .Y (add_21_2_n_58));
  CLKINVX1 add_21_2_fopt260(.A (add_21_2_n_57), .Y (add_21_2_n_59));
  CLKINVX1 add_21_2_fopt261(.A (add_21_2_n_22), .Y (add_21_2_n_57));
  BUFX2 add_21_2_fopt264(.A (add_21_2_n_66), .Y (add_21_2_n_64));
  INVXL add_21_2_fopt265(.A (add_21_2_n_66), .Y (add_21_2_n_65));
  INVXL add_21_2_fopt266(.A (add_21_2_n_14), .Y (add_21_2_n_66));
  CLKINVX2 add_21_2_fopt267(.A (add_21_2_n_14), .Y (add_21_2_n_67));
  INVXL add_21_2_fopt268(.A (add_21_2_n_70), .Y (add_21_2_n_69));
  INVXL add_21_2_fopt269(.A (in1[2]), .Y (add_21_2_n_70));
  CLKINVX20 add_21_2_fopt270(.A (in1[2]), .Y (add_21_2_n_71));
  BUFX2 add_21_2_fopt273(.A (add_21_2_n_12), .Y (add_21_2_n_76));
endmodule


