`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:22:57 CST (May  4 2021 16:22:57 UTC)

module DC_Filter_Mul_9Ux3U_12U_4(in2, in1, out1);
  input [8:0] in2;
  input [2:0] in1;
  output [11:0] out1;
  wire [8:0] in2;
  wire [2:0] in1;
  wire [11:0] out1;
  wire mul_22_8_n_0, mul_22_8_n_1, mul_22_8_n_2, mul_22_8_n_3,
       mul_22_8_n_4, mul_22_8_n_5, mul_22_8_n_6, mul_22_8_n_7;
  wire mul_22_8_n_8, mul_22_8_n_9, mul_22_8_n_10, mul_22_8_n_12,
       mul_22_8_n_13, mul_22_8_n_14, mul_22_8_n_15, mul_22_8_n_16;
  wire mul_22_8_n_17, mul_22_8_n_18, mul_22_8_n_19, mul_22_8_n_20,
       mul_22_8_n_21, mul_22_8_n_22, mul_22_8_n_23, mul_22_8_n_24;
  wire mul_22_8_n_25, mul_22_8_n_26, mul_22_8_n_27, mul_22_8_n_28,
       mul_22_8_n_29, mul_22_8_n_31, mul_22_8_n_32, mul_22_8_n_33;
  wire mul_22_8_n_34, mul_22_8_n_35, mul_22_8_n_36, mul_22_8_n_37,
       mul_22_8_n_38, mul_22_8_n_39, mul_22_8_n_40, mul_22_8_n_41;
  wire mul_22_8_n_42, mul_22_8_n_43, mul_22_8_n_44, mul_22_8_n_45,
       mul_22_8_n_46, mul_22_8_n_47, mul_22_8_n_48, mul_22_8_n_49;
  wire mul_22_8_n_50, mul_22_8_n_51, mul_22_8_n_52, mul_22_8_n_53,
       mul_22_8_n_54, mul_22_8_n_55, mul_22_8_n_56, mul_22_8_n_57;
  wire mul_22_8_n_58, mul_22_8_n_59, mul_22_8_n_60, mul_22_8_n_61,
       mul_22_8_n_62, mul_22_8_n_63, mul_22_8_n_65, mul_22_8_n_66;
  wire mul_22_8_n_68, mul_22_8_n_69, mul_22_8_n_71, mul_22_8_n_72,
       mul_22_8_n_73, mul_22_8_n_76, mul_22_8_n_77, mul_22_8_n_79;
  wire mul_22_8_n_81;
  ADDFX1 mul_22_8_g714(.A (mul_22_8_n_81), .B (mul_22_8_n_35), .CI
       (mul_22_8_n_20), .CO (out1[11]), .S (out1[10]));
  ADDFX1 mul_22_8_g715(.A (mul_22_8_n_79), .B (mul_22_8_n_36), .CI
       (mul_22_8_n_41), .CO (mul_22_8_n_81), .S (out1[9]));
  ADDFX1 mul_22_8_g716(.A (mul_22_8_n_76), .B (mul_22_8_n_42), .CI
       (mul_22_8_n_43), .CO (mul_22_8_n_79), .S (out1[8]));
  XNOR2X1 mul_22_8_g717(.A (mul_22_8_n_58), .B (mul_22_8_n_77), .Y
       (out1[7]));
  AOI21X1 mul_22_8_g718(.A0 (mul_22_8_n_56), .A1 (mul_22_8_n_73), .B0
       (mul_22_8_n_53), .Y (mul_22_8_n_77));
  OAI211X1 mul_22_8_g719(.A0 (mul_22_8_n_61), .A1 (mul_22_8_n_71), .B0
       (mul_22_8_n_66), .C0 (mul_22_8_n_51), .Y (mul_22_8_n_76));
  XNOR2X1 mul_22_8_g720(.A (mul_22_8_n_60), .B (mul_22_8_n_73), .Y
       (out1[6]));
  XNOR2X1 mul_22_8_g721(.A (mul_22_8_n_59), .B (mul_22_8_n_72), .Y
       (out1[5]));
  NAND2X1 mul_22_8_g722(.A (mul_22_8_n_65), .B (mul_22_8_n_71), .Y
       (mul_22_8_n_73));
  NOR2BX1 mul_22_8_g723(.AN (mul_22_8_n_69), .B (mul_22_8_n_52), .Y
       (mul_22_8_n_72));
  NAND2BX1 mul_22_8_g724(.AN (mul_22_8_n_69), .B (mul_22_8_n_50), .Y
       (mul_22_8_n_71));
  XNOR2X1 mul_22_8_g725(.A (mul_22_8_n_62), .B (mul_22_8_n_68), .Y
       (out1[4]));
  NAND2X1 mul_22_8_g726(.A (mul_22_8_n_49), .B (mul_22_8_n_68), .Y
       (mul_22_8_n_69));
  ADDFX1 mul_22_8_g727(.A (mul_22_8_n_63), .B (mul_22_8_n_37), .CI
       (mul_22_8_n_31), .CO (mul_22_8_n_68), .S (out1[3]));
  OA22X1 mul_22_8_g728(.A0 (mul_22_8_n_61), .A1 (mul_22_8_n_65), .B0
       (mul_22_8_n_54), .B1 (mul_22_8_n_57), .Y (mul_22_8_n_66));
  AOI21X1 mul_22_8_g729(.A0 (mul_22_8_n_52), .A1 (mul_22_8_n_50), .B0
       (mul_22_8_n_55), .Y (mul_22_8_n_65));
  ADDFX1 mul_22_8_g730(.A (mul_22_8_n_28), .B (mul_22_8_n_19), .CI
       (mul_22_8_n_32), .CO (mul_22_8_n_63), .S (out1[2]));
  NAND2BX1 mul_22_8_g731(.AN (mul_22_8_n_52), .B (mul_22_8_n_49), .Y
       (mul_22_8_n_62));
  NAND2BXL mul_22_8_g732(.AN (mul_22_8_n_57), .B (mul_22_8_n_56), .Y
       (mul_22_8_n_61));
  NAND2X1 mul_22_8_g733(.A (mul_22_8_n_54), .B (mul_22_8_n_56), .Y
       (mul_22_8_n_60));
  NOR2BX1 mul_22_8_g734(.AN (mul_22_8_n_50), .B (mul_22_8_n_55), .Y
       (mul_22_8_n_59));
  NOR2BX1 mul_22_8_g735(.AN (mul_22_8_n_51), .B (mul_22_8_n_57), .Y
       (mul_22_8_n_58));
  NOR2X1 mul_22_8_g736(.A (mul_22_8_n_40), .B (mul_22_8_n_44), .Y
       (mul_22_8_n_57));
  NAND2X1 mul_22_8_g737(.A (mul_22_8_n_45), .B (mul_22_8_n_38), .Y
       (mul_22_8_n_56));
  NOR2X1 mul_22_8_g738(.A (mul_22_8_n_47), .B (mul_22_8_n_46), .Y
       (mul_22_8_n_55));
  INVX1 mul_22_8_g739(.A (mul_22_8_n_53), .Y (mul_22_8_n_54));
  NOR2X1 mul_22_8_g740(.A (mul_22_8_n_45), .B (mul_22_8_n_38), .Y
       (mul_22_8_n_53));
  NOR2X1 mul_22_8_g741(.A (mul_22_8_n_39), .B (mul_22_8_n_48), .Y
       (mul_22_8_n_52));
  NAND2XL mul_22_8_g742(.A (mul_22_8_n_40), .B (mul_22_8_n_44), .Y
       (mul_22_8_n_51));
  NAND2X1 mul_22_8_g743(.A (mul_22_8_n_47), .B (mul_22_8_n_46), .Y
       (mul_22_8_n_50));
  NAND2X1 mul_22_8_g744(.A (mul_22_8_n_39), .B (mul_22_8_n_48), .Y
       (mul_22_8_n_49));
  ADDFX1 mul_22_8_g745(.A (mul_22_8_n_17), .B (mul_22_8_n_14), .CI
       (mul_22_8_n_1), .CO (mul_22_8_n_47), .S (mul_22_8_n_48));
  ADDFX1 mul_22_8_g746(.A (mul_22_8_n_18), .B (mul_22_8_n_5), .CI
       (mul_22_8_n_2), .CO (mul_22_8_n_45), .S (mul_22_8_n_46));
  ADDFX1 mul_22_8_g747(.A (mul_22_8_n_9), .B (mul_22_8_n_4), .CI
       (mul_22_8_n_0), .CO (mul_22_8_n_43), .S (mul_22_8_n_44));
  ADDFX1 mul_22_8_g748(.A (mul_22_8_n_10), .B (mul_22_8_n_3), .CI
       (mul_22_8_n_6), .CO (mul_22_8_n_41), .S (mul_22_8_n_42));
  OAI22X1 mul_22_8_g749(.A0 (mul_22_8_n_25), .A1 (mul_22_8_n_27), .B0
       (mul_22_8_n_22), .B1 (mul_22_8_n_21), .Y (mul_22_8_n_40));
  OA22X1 mul_22_8_g750(.A0 (mul_22_8_n_24), .A1 (mul_22_8_n_33), .B0
       (mul_22_8_n_23), .B1 (mul_22_8_n_12), .Y (mul_22_8_n_39));
  XNOR2X1 mul_22_8_g751(.A (mul_22_8_n_25), .B (mul_22_8_n_29), .Y
       (mul_22_8_n_38));
  XNOR2X1 mul_22_8_g752(.A (mul_22_8_n_24), .B (mul_22_8_n_34), .Y
       (mul_22_8_n_37));
  ADDHX1 mul_22_8_g753(.A (mul_22_8_n_15), .B (mul_22_8_n_16), .CO
       (mul_22_8_n_35), .S (mul_22_8_n_36));
  ADDHX1 mul_22_8_g754(.A (mul_22_8_n_23), .B (mul_22_8_n_12), .CO
       (mul_22_8_n_33), .S (mul_22_8_n_34));
  ADDHX1 mul_22_8_g755(.A (mul_22_8_n_7), .B (mul_22_8_n_8), .CO
       (mul_22_8_n_31), .S (mul_22_8_n_32));
  AOI21X1 mul_22_8_g756(.A0 (mul_22_8_n_13), .A1 (mul_22_8_n_26), .B0
       (mul_22_8_n_28), .Y (out1[1]));
  XNOR2X1 mul_22_8_g757(.A (mul_22_8_n_22), .B (mul_22_8_n_21), .Y
       (mul_22_8_n_29));
  NOR2X1 mul_22_8_g758(.A (mul_22_8_n_13), .B (mul_22_8_n_26), .Y
       (mul_22_8_n_28));
  AND2XL mul_22_8_g759(.A (mul_22_8_n_22), .B (mul_22_8_n_21), .Y
       (mul_22_8_n_27));
  AND2XL mul_22_8_g760(.A (in2[8]), .B (in1[2]), .Y (mul_22_8_n_20));
  AND2XL mul_22_8_g761(.A (in2[0]), .B (in1[2]), .Y (mul_22_8_n_19));
  NAND2X1 mul_22_8_g762(.A (in2[1]), .B (in1[0]), .Y (mul_22_8_n_26));
  NAND2X1 mul_22_8_g763(.A (in2[4]), .B (in1[2]), .Y (mul_22_8_n_25));
  NAND2X1 mul_22_8_g764(.A (in2[3]), .B (in1[2]), .Y (mul_22_8_n_18));
  NAND2X1 mul_22_8_g765(.A (in2[2]), .B (in1[2]), .Y (mul_22_8_n_17));
  AND2XL mul_22_8_g766(.A (in2[8]), .B (in1[1]), .Y (mul_22_8_n_16));
  AND2XL mul_22_8_g767(.A (in2[7]), .B (in1[2]), .Y (mul_22_8_n_15));
  NAND2X1 mul_22_8_g768(.A (in2[1]), .B (in1[2]), .Y (mul_22_8_n_24));
  NAND2X1 mul_22_8_g769(.A (in2[2]), .B (in1[1]), .Y (mul_22_8_n_23));
  NAND2X1 mul_22_8_g770(.A (in2[4]), .B (in1[0]), .Y (mul_22_8_n_14));
  NAND2X1 mul_22_8_g771(.A (in2[5]), .B (in1[1]), .Y (mul_22_8_n_22));
  NAND2X1 mul_22_8_g772(.A (in2[6]), .B (in1[0]), .Y (mul_22_8_n_21));
  AND2XL mul_22_8_g773(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  NAND2X1 mul_22_8_g774(.A (in2[0]), .B (in1[1]), .Y (mul_22_8_n_13));
  AND2XL mul_22_8_g775(.A (in2[7]), .B (in1[1]), .Y (mul_22_8_n_10));
  AND2XL mul_22_8_g776(.A (in2[6]), .B (in1[1]), .Y (mul_22_8_n_9));
  AND2XL mul_22_8_g777(.A (in2[2]), .B (in1[0]), .Y (mul_22_8_n_8));
  AND2XL mul_22_8_g778(.A (in2[1]), .B (in1[1]), .Y (mul_22_8_n_7));
  AND2XL mul_22_8_g779(.A (in2[6]), .B (in1[2]), .Y (mul_22_8_n_6));
  NAND2X1 mul_22_8_g780(.A (in2[5]), .B (in1[0]), .Y (mul_22_8_n_5));
  AND2XL mul_22_8_g781(.A (in2[7]), .B (in1[0]), .Y (mul_22_8_n_4));
  AND2XL mul_22_8_g782(.A (in2[8]), .B (in1[0]), .Y (mul_22_8_n_3));
  NAND2X1 mul_22_8_g783(.A (in2[4]), .B (in1[1]), .Y (mul_22_8_n_2));
  NAND2X1 mul_22_8_g784(.A (in2[3]), .B (in1[1]), .Y (mul_22_8_n_1));
  AND2XL mul_22_8_g785(.A (in2[5]), .B (in1[2]), .Y (mul_22_8_n_0));
  NAND2X1 mul_22_8_g786(.A (in2[3]), .B (in1[0]), .Y (mul_22_8_n_12));
endmodule


