`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:43:15 CST (May  4 2021 16:43:15 UTC)

module DC_Filter_Add_12U_290_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_1, add_21_2_n_2, add_21_2_n_3, add_21_2_n_4,
       add_21_2_n_7, add_21_2_n_8, add_21_2_n_9, add_21_2_n_10;
  wire add_21_2_n_11, add_21_2_n_12, add_21_2_n_13, add_21_2_n_15,
       add_21_2_n_16, add_21_2_n_17, add_21_2_n_18, add_21_2_n_19;
  wire add_21_2_n_20, add_21_2_n_22, add_21_2_n_24, add_21_2_n_25,
       add_21_2_n_26, add_21_2_n_29, add_21_2_n_30, add_21_2_n_33;
  wire add_21_2_n_57, add_21_2_n_60, add_21_2_n_61, add_21_2_n_62,
       add_21_2_n_64, add_21_2_n_65, add_21_2_n_66, add_21_2_n_67;
  wire add_21_2_n_68;
  INVX1 g7(.A (in1[0]), .Y (out1[0]));
  MXI2XL add_21_2_g210(.A (add_21_2_n_61), .B (add_21_2_n_60), .S0
       (add_21_2_n_30), .Y (out1[6]));
  MXI2X1 add_21_2_g211(.A (add_21_2_n_3), .B (in1[9]), .S0
       (add_21_2_n_33), .Y (out1[9]));
  ADDHX1 add_21_2_g212(.A (in1[8]), .B (add_21_2_n_24), .CO
       (add_21_2_n_33), .S (out1[8]));
  NAND2BXL add_21_2_g213(.AN (add_21_2_n_30), .B (add_21_2_n_29), .Y
       (out1[5]));
  MXI2X1 add_21_2_g215(.A (add_21_2_n_2), .B (in1[10]), .S0
       (add_21_2_n_1), .Y (out1[10]));
  AOI21X1 add_21_2_g216(.A0 (add_21_2_n_66), .A1 (add_21_2_n_57), .B0
       (in1[5]), .Y (add_21_2_n_30));
  NAND3XL add_21_2_g217(.A (in1[5]), .B (add_21_2_n_65), .C
       (add_21_2_n_57), .Y (add_21_2_n_29));
  MXI2XL add_21_2_g218(.A (add_21_2_n_8), .B (in1[7]), .S0
       (add_21_2_n_25), .Y (out1[7]));
  MXI2XL add_21_2_g219(.A (add_21_2_n_4), .B (in1[3]), .S0
       (add_21_2_n_19), .Y (out1[3]));
  NAND2X1 add_21_2_g221(.A (add_21_2_n_15), .B (add_21_2_n_24), .Y
       (add_21_2_n_26));
  AOI21X1 add_21_2_g222(.A0 (add_21_2_n_13), .A1 (add_21_2_n_57), .B0
       (add_21_2_n_10), .Y (add_21_2_n_25));
  NAND2X2 add_21_2_g224(.A (add_21_2_n_16), .B (add_21_2_n_22), .Y
       (add_21_2_n_24));
  XOR2XL add_21_2_g225(.A (add_21_2_n_65), .B (add_21_2_n_57), .Y
       (out1[4]));
  NAND2X2 add_21_2_g226(.A (add_21_2_n_13), .B (add_21_2_n_18), .Y
       (add_21_2_n_22));
  NAND2BXL add_21_2_g227(.AN (add_21_2_n_19), .B (add_21_2_n_20), .Y
       (out1[2]));
  NAND2X1 add_21_2_g228(.A (in1[2]), .B (add_21_2_n_17), .Y
       (add_21_2_n_20));
  NOR2X1 add_21_2_g229(.A (in1[2]), .B (add_21_2_n_17), .Y
       (add_21_2_n_19));
  NAND2X4 add_21_2_g230(.A (add_21_2_n_9), .B (add_21_2_n_11), .Y
       (add_21_2_n_18));
  INVX1 add_21_2_g231(.A (add_21_2_n_11), .Y (add_21_2_n_17));
  AOI21X2 add_21_2_g232(.A0 (in1[6]), .A1 (in1[5]), .B0 (in1[7]), .Y
       (add_21_2_n_16));
  NOR2X1 add_21_2_g233(.A (add_21_2_n_2), .B (add_21_2_n_12), .Y
       (add_21_2_n_15));
  MXI2XL add_21_2_g234(.A (in1[1]), .B (add_21_2_n_7), .S0 (in1[0]), .Y
       (out1[1]));
  NOR2X4 add_21_2_g235(.A (add_21_2_n_64), .B (add_21_2_n_68), .Y
       (add_21_2_n_13));
  NAND2X1 add_21_2_g236(.A (in1[9]), .B (in1[8]), .Y (add_21_2_n_12));
  NOR2X6 add_21_2_g237(.A (in1[1]), .B (in1[0]), .Y (add_21_2_n_11));
  NOR2BX1 add_21_2_g238(.AN (in1[5]), .B (add_21_2_n_62), .Y
       (add_21_2_n_10));
  NOR2X8 add_21_2_g239(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_9));
  INVXL add_21_2_g240(.A (in1[7]), .Y (add_21_2_n_8));
  INVX1 add_21_2_g241(.A (in1[1]), .Y (add_21_2_n_7));
  INVXL add_21_2_g245(.A (in1[3]), .Y (add_21_2_n_4));
  INVX1 add_21_2_g246(.A (in1[9]), .Y (add_21_2_n_3));
  INVX1 add_21_2_g247(.A (in1[10]), .Y (add_21_2_n_2));
  NOR2BX1 add_21_2_g2(.AN (add_21_2_n_24), .B (add_21_2_n_12), .Y
       (add_21_2_n_1));
  XNOR2XL add_21_2_g248(.A (in1[11]), .B (add_21_2_n_26), .Y
       (out1[11]));
  BUFX3 add_21_2_fopt(.A (add_21_2_n_18), .Y (add_21_2_n_57));
  INVXL add_21_2_fopt249(.A (add_21_2_n_61), .Y (add_21_2_n_60));
  INVXL add_21_2_fopt250(.A (add_21_2_n_62), .Y (add_21_2_n_61));
  CLKINVX1 add_21_2_fopt251(.A (in1[6]), .Y (add_21_2_n_62));
  CLKINVX20 add_21_2_fopt252(.A (in1[6]), .Y (add_21_2_n_64));
  INVXL add_21_2_fopt253(.A (add_21_2_n_67), .Y (add_21_2_n_65));
  INVXL add_21_2_fopt254(.A (add_21_2_n_67), .Y (add_21_2_n_66));
  INVXL add_21_2_fopt255(.A (in1[4]), .Y (add_21_2_n_67));
  CLKINVX4 add_21_2_fopt256(.A (in1[4]), .Y (add_21_2_n_68));
endmodule


