`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 00:43:13 CST (May  4 2021 16:43:13 UTC)

module DC_Filter_Add_12U_287_1(in1, out1);
  input [11:0] in1;
  output [11:0] out1;
  wire [11:0] in1;
  wire [11:0] out1;
  wire add_21_2_n_0, add_21_2_n_2, add_21_2_n_5, add_21_2_n_6,
       add_21_2_n_7, add_21_2_n_8, add_21_2_n_9, add_21_2_n_10;
  wire add_21_2_n_11, add_21_2_n_12, add_21_2_n_13, add_21_2_n_14,
       add_21_2_n_16, add_21_2_n_17, add_21_2_n_18, add_21_2_n_19;
  wire add_21_2_n_21, add_21_2_n_22, add_21_2_n_23, add_21_2_n_26,
       add_21_2_n_27, add_21_2_n_28;
  assign out1[0] = in1[0];
  assign out1[1] = in1[1];
  INVX1 g7(.A (in1[2]), .Y (out1[2]));
  MXI2X1 add_21_2_g208(.A (add_21_2_n_6), .B (in1[9]), .S0
       (add_21_2_n_23), .Y (out1[9]));
  NAND2BX1 add_21_2_g210(.AN (add_21_2_n_26), .B (add_21_2_n_28), .Y
       (out1[11]));
  MXI2X1 add_21_2_g211(.A (add_21_2_n_9), .B (in1[10]), .S0
       (add_21_2_n_2), .Y (out1[10]));
  OAI21X1 add_21_2_g212(.A0 (add_21_2_n_16), .A1 (add_21_2_n_21), .B0
       (in1[11]), .Y (add_21_2_n_28));
  NOR2X1 add_21_2_g214(.A (in1[5]), .B (add_21_2_n_19), .Y
       (add_21_2_n_27));
  NOR3X1 add_21_2_g215(.A (in1[11]), .B (add_21_2_n_16), .C
       (add_21_2_n_21), .Y (add_21_2_n_26));
  MXI2XL add_21_2_g217(.A (in1[7]), .B (add_21_2_n_5), .S0
       (add_21_2_n_22), .Y (out1[7]));
  MXI2XL add_21_2_g218(.A (in1[8]), .B (add_21_2_n_8), .S0
       (add_21_2_n_21), .Y (out1[8]));
  NOR2X1 add_21_2_g220(.A (add_21_2_n_8), .B (add_21_2_n_21), .Y
       (add_21_2_n_23));
  OAI21X1 add_21_2_g221(.A0 (add_21_2_n_13), .A1 (add_21_2_n_14), .B0
       (add_21_2_n_12), .Y (add_21_2_n_22));
  NOR2X2 add_21_2_g222(.A (add_21_2_n_17), .B (add_21_2_n_18), .Y
       (add_21_2_n_21));
  MXI2XL add_21_2_g223(.A (in1[4]), .B (add_21_2_n_10), .S0
       (add_21_2_n_14), .Y (out1[4]));
  NOR2X1 add_21_2_g224(.A (add_21_2_n_10), .B (add_21_2_n_14), .Y
       (add_21_2_n_19));
  NOR2X2 add_21_2_g225(.A (add_21_2_n_14), .B (add_21_2_n_13), .Y
       (add_21_2_n_18));
  NAND2X4 add_21_2_g226(.A (add_21_2_n_12), .B (add_21_2_n_5), .Y
       (add_21_2_n_17));
  NAND2X2 add_21_2_g227(.A (in1[10]), .B (add_21_2_n_11), .Y
       (add_21_2_n_16));
  MXI2XL add_21_2_g228(.A (in1[3]), .B (add_21_2_n_7), .S0 (in1[2]), .Y
       (out1[3]));
  NOR2X8 add_21_2_g229(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_14));
  NAND2X6 add_21_2_g230(.A (in1[6]), .B (in1[4]), .Y (add_21_2_n_13));
  NAND2X8 add_21_2_g231(.A (in1[6]), .B (in1[5]), .Y (add_21_2_n_12));
  NOR2X4 add_21_2_g233(.A (add_21_2_n_6), .B (add_21_2_n_8), .Y
       (add_21_2_n_11));
  INVX1 add_21_2_g234(.A (in1[4]), .Y (add_21_2_n_10));
  INVXL add_21_2_g237(.A (in1[10]), .Y (add_21_2_n_9));
  CLKINVX2 add_21_2_g238(.A (in1[8]), .Y (add_21_2_n_8));
  INVX1 add_21_2_g239(.A (in1[3]), .Y (add_21_2_n_7));
  CLKINVX3 add_21_2_g240(.A (in1[9]), .Y (add_21_2_n_6));
  CLKINVX2 add_21_2_g241(.A (in1[7]), .Y (add_21_2_n_5));
  OR2XL add_21_2_g2(.A (add_21_2_n_0), .B (add_21_2_n_27), .Y
       (out1[5]));
  NOR2BX1 add_21_2_g242(.AN (add_21_2_n_11), .B (add_21_2_n_21), .Y
       (add_21_2_n_2));
  XNOR2X1 add_21_2_g243(.A (in1[6]), .B (add_21_2_n_27), .Y (out1[6]));
  NOR3BXL add_21_2_g244(.AN (in1[5]), .B (add_21_2_n_10), .C
       (add_21_2_n_14), .Y (add_21_2_n_0));
endmodule


